### ISSUE TITLE
Collection of Models always has the resourceKey 'data'

### ISSUE THREAD

**Issue by ductiletoaster** [flugger/laravel-responder#101]
When dealing with Collections it seems we always are given the resource key 'data'. 

It seems that in:
`Flugg\Responder\Serializers\SuccessSerializer`

'data' is hard coded in a few places. Changing it in the method `collection` also fails the application expects to see the generic key.

Using the override doesn't seem to work
`
return $this->responder->success($phone, $transformer, 'phones')->respond(Response::HTTP_OK);
`
Nor does setting `getResourceKey` on the models within the collection.

To replicate I simply did a where clause on the model I was interested in.

**Comment by flugger** [comment]
Hey! The `data` field in the serializer is intentionally hardcoded so you have a consistent way of fetching data from the API. The resource key is current only used for the sparse fieldset feature as far as I recall. 

Feel free to make your own serializer extending SuccessSerializer which changes `data` to the resource key.

**Comment by ductiletoaster** [comment]
I tried extending and doing the following but then responder throws an exception:
```
    public function collection($resourceKey, array $data)
    {
        return [$resourceKey => $data];
    }
```

**Comment by flugger** [comment]
I can't seem to replicate. I have two models: users and tasks. I'm returning a list of users with associated tasks:

```php
return responder()
        ->success(User::all())
        ->serializer(NewSuccessSerializer::class)
        ->with('tasks')
        ->respond();
```

This returns `users` instead of `data`:

```json
{
    "status": 200,
    "success": true,
    "users": [
        ...
        "tasks": [
             ...
        ]
    ]
}
```

Where `NewSuccessSerializer` only overrides the `item` and `collection` methods:

```php
<?php

namespace App\Serializers;

use Flugg\Responder\Serializers\SuccessSerializer;

class NewSuccessSerializer extends SuccessSerializer
{
    public function collection($resourceKey, array $data)
    {
        return [$resourceKey => $data];
    }

    public function item($resourceKey, array $data)
    {
        return [$resourceKey => $data];
    }
}
```

Am I missing something or does this solve your problem?

**Comment by flugger** [comment]
@ductiletoaster Any updates on this?

**Comment by flugger** [comment]
I'll close this due to inactivity, but let me know if you still have problems and I'll gladly assist!

**Comment by colinpade** [comment]
For the record I had this same issue and did the solution @flugger posted
