### ISSUE TITLE
Transform of array of models throw an error when it is used after an array_filter

### ISSUE THREAD

**Issue by IlCallo** [flugger/laravel-responder#110]
Hey, I got another interesting problem.
I don't really know it's exact location in the code this time, unluckily.
I'm on Laravel 5.6.

The problem rises when I try to transform an array of Models, after I filtered it with the `array_filter` function.

On my User model I have a simil-relation of Activities: a function which fuses together two actual relations using Laravel Collections methods and return an array of Activity models using the `all()` method.
It actually works fine with laravel-responder... until I do a filter on it.
In that case, when checking a policy for it, the system will just tell me

    Type error: Argument 1 passed to App\Transformers\ActivityTransformer::transform() must be an instance of App\Activity, array given

which doesn't make much sense, because I checked and the `array_filter` does not alter the structure or type of the data: an array of Activity models enters, an array of Activity models exits.

What happen is that during the policy checking, two relations are accessed (which means that they get loaded): the Activity owner and others Activity members.

Members Activity's relation generates a recursion (because it tryes to load itself into the pivot of the relation) but it shouldn't be a problem, because `members` relation cannot be loaded by the transformer (it's not present in the `$load` nor `$relations` properties).

Owner, on the other hand, should be loaded automatically, but it doesn't have recursions or other similar problems.

And here comes the funny thing: wrapping the array returned by the filter in a `collect()` helper solves the problem. The transformer stop complaining and everything runs smoothly.
I tryed to pin-point the bug with a test, but I could not replicate the behaviour.

To me it seems that the problem is somewhere hidden in the code which decides when an array is considered as a primitive array or as an array of Models, and it says `array given` because the whole array of Activity models is given instead of running a `transform()` for every array element.
The other option is that the `all()` method of Laravel Collections doesn't actually return an array but something which still carries with him the info that it was a Collection before, which allow laravel-responder to guess the real nature of the array.
Which seems really strange, given the type checks I did while debugging (both variable are arrays which contains Activity models) and the method description: `The all method returns the underlying array represented by the collection`.

Any ideas? The bug is fixed, but I cannot sleep well knowing that it could still come back as a regression bug in some time :P

It could be that the bug is actually the reverse of my use case and the system shall *not* process an array as a Collection at all, but I could not find it written in the docs.

**Comment by flugger** [comment]
I think the problem is that the array ends up having non-sequential numeric keys after the filter and therefore is treated as an associative array. Does wrapping the `array_filter` in an `array_values` solve the issue?

**Comment by IlCallo** [comment]
Yep, that was definitely the issue, I wasn't aware of this behaviour, my bad, thank you :)

For sake of knowledge, who or what checks sequentiality in this case? Is it laravel-responder, Fractal, Laravel or PHP itself which decides what to do?

**Comment by flugger** [comment]
Laravel's `isAssoc` method is used on the `Arr` class which just checks that the keys are equal: https://github.com/laravel/framework/blob/5.6/src/Illuminate/Support/Arr.php#L357.

However, it should be noted that native PHP seems to behave the same way. For instance, using `json_encode`, the following outputs an array:

```php
json_encode([0 => 'foo', 1 => 'bar', 2 => 'baz'])
```

While this will output an object:

```php
json_encode([0 => 'foo', 2 => 'bar', 3 => 'baz'])
```

**Comment by IlCallo** [comment]
Yeah, I knew about JSON behaviour, it makes sense that Laravel adapted to that.
Thank you 🙇
Maybe it could be useful to write something about it in the docs?

**Comment by flugger** [comment]
Yeah, it could probably be added as a notice box somewhere

**Comment by IlCallo** [comment]
I can try a PR in some days, if you want

**Comment by flugger** [comment]
Sure, I'd appreciate that :)
