### ISSUE TITLE
Transforming relation only

### ISSUE THREAD

**Issue by Hesesses** [flugger/laravel-responder#123]
I have complex query and I would like to use transformer for one relationship only:
`transformation($lists)->with('values')->transform();`

Now it uses ListTransformer for $lists and I would like to have $lists as it is and only `values` would be transformed using ValueTransformer.

Is this possible?

**Comment by flugger** [comment]
There isn't currently a way to specify related transformers without a transformer class. I suppose you could create a transformer that just returns the list without modifications and also includes `values`:

```php
class ComplexListTransformer
{

    protected $relations = ['values' => ValueTransformer::class];
    public function transform($list): array
    {
         return $list->toArray();
    }
}
```
