### ISSUE TITLE
Reponse problem

### ISSUE THREAD

**Issue by Kohan90** [flugger/laravel-responder#13]
I can't seem to figure out why the successResponse() method returns the same object in all array keys. Before i call the reponse method i have a Collection with 2 different objects and the response is a JSON with 2 exactly same objects. From what i tried I saw that the toArray() method does that. Mention i'm using Laravel 5.3.*.

**Comment by flugger** [comment]
If I understand you correctly, you send in an array with 2 different model objects and end up up with a JSON containing only one of them, twice? Could you paste the data you send in to the successResponse method?

**Comment by Kohan90** [comment]
Hello there,
Here is an example of Collection that I send as a parameter to the successResponse method:
Collection {#170
  #items: array:2 [
    0 => Partner {#171
      #connection: null
      #table: null
      #primaryKey: "id"
      #keyType: "int"
      #perPage: 15
      +incrementing: true
      +timestamps: true
      #attributes: array:13 [
        "id" => 1
        "name" => "Vodafone"
        "email" => "vdf@vodafone.ro"
        "phone" => "0724586748"
        "size" => "400"
        "billing_details" => "Date de facturare"
        "cui" => "4535321"
        "ro" => "125432"
        "bank_account" => "ROING3454543535234432"
        "status" => "1"
        "deleted_at" => null
        "created_at" => null
        "updated_at" => null
      ]
      #original: array:13 [
        "id" => 1
        "name" => "Vodafone"
        "email" => "vdf@vodafone.ro"
        "phone" => "0724586748"
        "size" => "400"
        "billing_details" => "Date de facturare"
        "cui" => "4535321"
        "ro" => "125432"
        "bank_account" => "ROING3454543535234432"
        "status" => "1"
        "deleted_at" => null
        "created_at" => null
        "updated_at" => null
      ]
      #relations: []
      #hidden: []
      #visible: []
      #appends: []
      #fillable: []
      #guarded: array:1 [
        0 => "*"
      ]
      #dates: []
      #dateFormat: null
      #casts: []
      #touches: []
      #observables: []
      #with: []
      +exists: true
      +wasRecentlyCreated: false
    }
    1 => Partner {#172
      #connection: null
      #table: null
      #primaryKey: "id"
      #keyType: "int"
      #perPage: 15
      +incrementing: true
      +timestamps: true
      #attributes: array:13 [
        "id" => 2
        "name" => "McDonalds"
        "email" => "mc@mc.com"
        "phone" => "0721454848"
        "size" => "200"
        "billing_details" => "Date facturare"
        "cui" => "43254353"
        "ro" => "2343242"
        "bank_account" => "ROBCR45354354365464"
        "status" => "1"
        "deleted_at" => null
        "created_at" => null
        "updated_at" => null
      ]
      #original: array:13 [
        "id" => 2
        "name" => "McDonalds"
        "email" => "mc@mc.com"
        "phone" => "0721454848"
        "size" => "200"
        "billing_details" => "Date facturare"
        "cui" => "43254353"
        "ro" => "2343242"
        "bank_account" => "ROBCR45354354365464"
        "status" => "1"
        "deleted_at" => null
        "created_at" => null
        "updated_at" => null
      ]
      #relations: []
      #hidden: []
      #visible: []
      #appends: []
      #fillable: []
      #guarded: array:1 [
        0 => "*"
      ]
      #dates: []
      #dateFormat: null
      #casts: []
      #touches: []
      #observables: []
      #with: []
      +exists: true
      +wasRecentlyCreated: false
    }
  ]
}

And the return is:
{
  "success": true,
  "data": [
    {
      "id": 1,
      "name": "Vodafone",
      "email": "vdf@vodafone.ro",
      "phone": "0724586748",
      "size": "400",
      "billing_details": "Date de facturare",
      "cui": "4535321",
      "ro": "125432",
      "bank_account": "ROING3454543535234432",
      "status": "1",
      "deleted_at": null,
      "created_at": null,
      "updated_at": null
    },
    {
      "id": 1,
      "name": "Vodafone",
      "email": "vdf@vodafone.ro",
      "phone": "0724586748",
      "size": "400",
      "billing_details": "Date de facturare",
      "cui": "4535321",
      "ro": "125432",
      "bank_account": "ROING3454543535234432",
      "status": "1",
      "deleted_at": null,
      "created_at": null,
      "updated_at": null
    }
  ]
}

As you can see is the same object twice.

**Comment by flugger** [comment]
Hey!

I managed to recreate the issue. Basically, when there is no transformer specified it will make its own closure transformer. There was however, a tiny bug related to that closure, and the fix was rather simple: https://github.com/flugger/laravel-responder/commit/b4ecd1d246d83d90f89936f20be30898be8a0d10

You can `composer update` to fetch the latest version (1.2.6) which contains the fix.

Thanks for finding the bug :)
