### ISSUE TITLE
Validation responder doesn't work

### ISSUE THREAD

**Issue by jurtjee1997** [flugger/laravel-responder#130]
Using laravel-responder, recently my validation responder doesn't work. I received a response back without laravel-responder. When my validation goes well I get laravel-responder back.

```
{
    "message": "The given data was invalid.",
    "errors": {
        "name": [
            "The name field is required."
        ]
    }
}
```
```
{
    "status": 200,
    "success": true,
    "data": {
        "id": "47",
        "name": "Jur",
    }
}
```
Does anyone have any idea what's going wrong here?

**Comment by flugger** [comment]
Hey @jurtjee1997,

Have you followed the steps from the documentation on handling exceptions? (https://github.com/flugger/laravel-responder#handling-exceptions)

If you use the package's exception handler it should automatically convert the Laravel's validation exception and display the correctly styled error message.
