### ISSUE TITLE
Exception from other package

### ISSUE THREAD

**Issue by jurtjee1997** [flugger/laravel-responder#131]
I'm using the [cartalyst-stripe ](https://github.com/cartalyst/stripe), but when i get a exception it isn't transformd into this responder. 

How can I fix it properly?

**Comment by flugger** [comment]
Only exceptions that extend from the package's `HttpException` will be transformed into a correctly formatted error response. The package already converts most of Laravel's built-in exceptions to a package exception. If you want to do the same with other exceptions you can convert the exception in the exception handler to your own version extending `HttpException`:

```php
$this->convert($exception, [
    CartalystException::class => MyCustomException::class
];
```

More information about converting exceptions can be found here: https://github.com/flugger/laravel-responder#handling-exceptions

Alternatively, you can catch the exception and do a regular `responder->error('cartalys_error')->respond()` to return an error message.

Hope this answers your question :)
