### ISSUE TITLE
Unable to set limit for relationship

### ISSUE THREAD

**Issue by erashdan** [flugger/laravel-responder#132]
I'm trying to set limit for relationship element 
(Every post has many comments) 
And only I want to return one comment from PostTransformer 

`
return responder()->success($posts)->with(['comments' => function($query) {
            $query->latest()->limit(1);
        }])->respond();
`

**Comment by flugger** [comment]
Apologises for not responding sooner. I can't of the top of my head say why this shouldn't work, but will do some investigation soon. Does this work when you don't use this package and adds the relation query manually? Like below:

```php
Post::with(['comments' => function($query) { 
    $query->latest()->limit(1);
}])->get();
```

**Comment by erashdan** [comment]
I solve it in transformer class by adding this method

```
public function includeComments(Post $post, Collection $parameters)
    {
        return $post->comments->sortByDesc('updated_at')->take(1);
    }
```

Many thanks
