### ISSUE TITLE
why can't $this->success(123)

### ISSUE THREAD

**Issue by aogg** [flugger/laravel-responder#137]
use \App\Helper\Vendor\MakesResponses

Argument $resource should be an instance of League\Fractal\Resource\Item or League\Fractal\Resource\Collection

![image](https://user-images.githubusercontent.com/8998031/55308852-75cd7880-548e-11e9-91dd-586f4747c7d5.png)

support  $this->success(123)

**Comment by flugger** [comment]
Hi, sorry for the delayed response. Unfortunately, this is a limitation with the Fractal library. It only supports Primitive values as nested values. The root value must be serializable as an array. You would have to do something like: 

```
$this->success(['number' => 123]);
```
