### ISSUE TITLE
[Question] Using TestHelper with codeception

### ISSUE THREAD

**Issue by computerfr33k** [flugger/laravel-responder#14]
Not sure if you are familiar with [codeception](http://codeception.com/for/laravel), but if you are I was wondering if it was possible to use your test helper methods with codeception api tests.

**Comment by flugger** [comment]
Never used Codeception, so afraid I can't help you there. However, the package testing helpers are basically just a wrapper around Laravel's own testing helpers, which is based on PHPUnit.

**Comment by computerfr33k** [comment]
Alright, guess I'll have to try and figure out if/how I can do it in codeception.

**Comment by flugger** [comment]
Let me know how it goes or if you meet on any issues :)
