### ISSUE TITLE
Misspelled word inside readme.me

### ISSUE THREAD

**Issue by rotiroti** [flugger/laravel-responder#15]
Hi flugger,

I've found a misspelled word inside your **readme.me** file regarding how to map a [Transformer](https://github.com/flugger/laravel-responder#mapping-transformers-to-models) to a model.

The model should implement the `Flugg\Responder\Contracts\Transformable` instead of `Flugg\Responder\Contract\Transformable` (note the *s* at the end of the word *Contracts*).

**Comment by flugger** [comment]
Fixed, thanks for the heads up!
