### ISSUE TITLE
How can i send error response of validation error of fields in lumen/laravel ?

### ISSUE THREAD

**Issue by royrakesh** [flugger/laravel-responder#150]
My code 
![image](https://user-images.githubusercontent.com/15174104/71778136-e2524680-2fcf-11ea-97a6-9d2421a9d250.png)

I want to send array of fields to response which has error but i got response in string 

Response

![image](https://user-images.githubusercontent.com/15174104/71778147-06158c80-2fd0-11ea-8147-b91997189f92.png)

**Comment by flugger** [comment]
Hi, the second paramter of `error` is for messages and can only contain strings. The `data` method should do what you're after:

```php
return responder()->error('errors')->data($validator->errors())->respond();
```

However, the package also automatically catches `ValidationException` and returns a neatly structured error response if you've followed the steps in the (https://github.com/flugger/laravel-responder#handling-exceptions)[Handling Exceptions] chapter of the documentation.

**Comment by royrakesh** [comment]
Thanks that works with one modification

`return responder()->error('errors')->data($validator->errors()->toArray())->respond();`
