### ISSUE TITLE
$relationship not returning data on nested relationship

### ISSUE THREAD

**Issue by wukongrita** [flugger/laravel-responder#152]
Hi @flugger 

I have:

LeadTransformer.php
```
protected $relations = [
    'customer',
];
```

CustomerTransformer.php
```
protected $relations = [
    'addresses',
];
```

```
GET /leads?with=customer // OK, return leads with customer data
GET /leads?with=customer,customer.addresses // ONLY return leads with customer data; without the addresses
```

if I change it to `$load`:

CustomerTransformer.php
```
protected $load = [
    'addresses',
];
```

```
GET /leads?with=customer // return leads with customer data and addresses; since it will load as default relations
```

Any Idea on how :

```
GET /leads?with=customer,customer.addresses // ONLY return leads with customer data; without the addresses
```

could also return with the related customer addresses by using it at the `$relations` ?

**Comment by flugger** [comment]
Hey @wukongrita! Sorry for the late response. Did you manage to find a solution to this? Have you tried to add a mapping to the transformers to the arrays:

```php
protected $relations = [
    'customer' => CustomerTransformer::class,
];
```

```php
protected $relations = [
    'addresses' => AddressTransformer::class,
];
```

**Comment by wukongrita** [comment]
Hi @flugger ,

I have try the solution and yes it's working and showing the relations.

As before, I already setup the model with the transformer in the `TransformerServiceProvider.php` like:

```
\App\Models\Lead::class => \App\Transformers\LeadTransformer::class,
\App\Models\Customer::class => \App\Transformers\CustomerTransformer::class,
\App\Models\Address::class => \App\Transformers\AddressTransformer::class,
```

I thought that by setting it in the Service Provider, it will automatically included too (but it is not)..

Then, by that mean; I got to map every `$relations` or `$load` to its Transformer Class, right?


Thank you..

**Comment by flugger** [comment]
Yeah, correct, the problem is that the package doesn’t know which models the “customer” or  “addresses” relate to until they are loaded.
