### ISSUE TITLE
Relationship filter parameters unsupported

### ISSUE THREAD

**Issue by imjohnbon** [flugger/laravel-responder#16]
I haven't had time to test this too thoroughly, I will try and update this issue with more information when I do, but it doesn't appear that fractal's nested relationships are working correctly when used with this package. By that I mean url patterns like this:

example.com/books?include=author.stores

Getting the "author" relationship works, but getting the ".stores" portion of it does not.

**Comment by flugger** [comment]
Hey! What version of the package are you using?

**Comment by imjohnbon** [comment]
I'm not on my home computer right now, but I ran composer update a day or 2 ago, and I believe I am on the latest version (1.2.7).

**Comment by flugger** [comment]
I know there has been an issue with nested relationships in the past, however, this should have been resolved in a prior patch. 

I can't seem to replicate the issue. Given the following code:

```php
$user = App\User::with('posts.comments')->first();

    return responder()->success($user);
```

The following JSON was outputted:

```json
{
    "status": 200,
    "success": true,
    "data": {
        "id": 1,
        "name": "Claude Cole Jr.",
        "email": "damaris67@example.org",
        "created_at": "2016-10-25 15:06:07",
        "updated_at": "2016-10-25 15:06:07",
        "posts": [
            {
                "id": 1,
                "content": "This is a post",
                "user_id": 1,
                "created_at": "2016-10-25 15:06:07",
                "updated_at": "2016-10-25 15:06:07",
                "comments": [
                    {
                         "id": 1,
                         "content": "This is a comment",
                         "post_id": 1,
                         "created_at": "2016-10-25 15:06:07",
                         "updated_at": "2016-10-25 15:06:07"
                    }
                ]
            }
        ]
    }
}
```

**Comment by imjohnbon** [comment]
Hmm, I will try to look into this further when I get home tonight then. Do you know if your example works when done through the "includes" parameter in the url of a route, rather than hard coded? For instance, like this:

`example.com/user?include=posts.comments`

Obviously you'd also need a route, controller, and transformers for the users and posts.

**Comment by flugger** [comment]
How are you loading the relations? It should work just as fine doing something along the lines of:

```php
$user = App\User::with(request()->include)->first();

return responder()->success($user);
```

**Comment by imjohnbon** [comment]
In my past experience with using Fractal directly, I never had to load anything directly like that (passing the includes from the request object into the query). I just instantiated Fractal like this:

`$fractal = new League\Fractal\Manager();`

Then loaded the includes from the URL:

`if (Input::get('include')) {
       $fractal->parseIncludes(Input::get('include'));
}`

Then whatever I put into the URL would just be lazy loaded automatically. Same way it's done in the docs (http://fractal.thephpleague.com/transformers/)[http://fractal.thephpleague.com/transformers/].

**Comment by flugger** [comment]
Yeah - this package works slightly different to be more in line with how Eloquent works. Basically, you don't have to call `parseIncludes()`, but instead pass in your data with the relations loaded (like the example above). Then the package will automatically catch all relations and call `parseIncludes()` on Fractal behind the scenes. :)

**Comment by imjohnbon** [comment]
Interesting! I apologize, as I see that this is in the documentation.

Honestly, what's really weird to me, is that in my current code this works:

`example.com/user?include=posts`

But this does not:

`example.com/user?include=posts.comments`

I don't use "with" to load the relationship in either case. But the second example does the same thing as the first, it returns the user with the posts, but NOT with the posts comments.

When I get back home, I'll try to pass the "include" property from the request to my query directly and see if that makes it work. Sorry, it's difficult for me to be more helpful when I'm not working on it hands-on.

**Comment by imjohnbon** [comment]
Okay, after working with this more, I believe I now understand how the relationship includes work with this package.

I absolutely see what you were going for, it's a very interesting idea. However, I'm not sure it's quite flexible enough. For instance, with Fractal you can do some crazy stuff with parameters like so:

`?include=comments:limit(5|1):order(created_at|desc).`

With this package, it doesn't seem that's possible, since there's no $availableIncludes parameter on the transformers and thus, no respective functions for loading relationships where you can do some business logic with those parameters.

Am I missing something or am I correct in thinking that you forfeit some of that flexibility when using this package since it tries to load relationships "auto-magically"?

**Comment by imjohnbon** [comment]
Sorry to spam you, but after playing around further, I realized I could get the relationships to work more like traditional Fractal's by changing like 142 in SuccessResponseBuilder.php from this:

`$this->manager->parseIncludes(array_merge($transformer->getRelations(), $this->resolveNestedRelations($resource->getData())));`

to this:

`$this->manager->parseIncludes(Input::get('include'));`

I think it would be really cool if you added an option to the config file for something like "smart-load-relationships". If it was set to true, it would work like it does currently. If it was set to false, it would work like my way above.

This package is by far the best fractal abstraction, awesome job on it. But I imagine I won't be the last person who needs some more flexibility when it comes to relationships. Having the option to switch your smart-loading on or off would be great for those situations.

**Comment by flugger** [comment]
Yeah, you're right, that is indeed a missing feature from Fractal. I still don't feel like Fractal's DSL (if I can even call it that) feels very Laravel-ish, and would optimally like to find a better solution for it. However, I'm all up for allowing an alternative syntax to load includes until I can find a better solution for it. 

What do you think of the following syntax:

```php
return responder()->transform($user)->include('posts,comments:limit(5|1)')->respond();
```

This could even work together with the existing solution. If you don't load any relations into `$user`, the package wont be doing any smart autoloading of relations.

**Comment by imjohnbon** [comment]
I think the problem with that syntax is that most of the time, people are going to be appending those includes to the URL's and not including them hardcoded like that. So you'd basically have to do this:

`return responder()->transform($user)->include(Input::get('include', []))->respond();`

**anywhere** in your controllers that you output your a model that might have includes. Personally, that feels the most un-laravelish to me. Also, with that proposed syntax, where would the logic for the "limit(5|1)" part go? Trying to figure that out auto-magically on your end would be incredibly hard, and would fail if I wanted to do something custom instead like "comments:only(best)" or whatever.

As much as I like the auto-magic stuff (the way you automatically detect transformers is my favorite part of this package), I think due to the highly customized way people sometimes need to use URL parameters, sticking with how Fractal typically handles it is the best solution. Maybe you could make a "smart_load_relationships" config option that would default to true, and if it was true it would work like it current does, but if it was false it would work like Fractal normally does?

**Comment by flugger** [comment]
I personally also load relations from query parameters, but I'm usually using 'with' instead of 'include', so if the package should pick up on relations automatically, I think it might be a good idea to include a config option for specifying which GET parameter to load relations from. 

```php
'loadRelationsFromParameter' => 'include' // or false to disable
```

That might require a bit of reworking of how the package currently works though. Where would you usually place the "limit(5|1)" logic in Fractal and what would it look like?

**Comment by imjohnbon** [comment]
Typically the parameter logic would be placed in the transformer, the same way you would normally load relationships via Fractal, like so:

`<?php

    use League\Fractal\ParamBag;

    private $availableIncludes = ['comments'];
    private $validParams = ['limit', 'order'];

    public function includeComments(Book $book, ParamBag $params = null)
    {
        if ($params === null) {
            return $book->comments;
        }

        list($limit, $offset) = $params->get('limit');
        list($orderCol, $orderBy) = $params->get('order');

        $comments = $book->comments
            ->take($limit)
            ->skip($offset)
            ->orderBy($orderCol, $orderBy)
            ->get();

        return $this->collection($comments, new CommentTransformer);
    }`

That was taken almost verbatim from the Transformers docs, btw: http://fractal.thephpleague.com/transformers/ Just ctrl+f "Include Parameters" to find the section.

**Comment by flugger** [comment]
Right, I see. I still suppose you end up with a lot of boilerplate code when you have to do the above for every relation? 

I've been thinking a bit about an alternative method for solving the issue. I'm imagining a scenario where you can place a 'Filterable' trait of some sort to every model you want to allow filtering on. Then the package can parse the request parameters and do the filtering if the model uses the trait. 

That way we get the best of both worlds, you can filter based on GET parameters and you wont need to make one method for every relation in your transformers. We can still allow `$availableIncludes` and `$validParams` to the transformers, which I think is important when just parsing the request object directly.

Would that be a suitable solution you think? :) 

Thanks for spending time on the issue!

**Comment by imjohnbon** [comment]
I think that's a decent solution, my concern again would be the flexibility. You're right that there is a bit of boilerplate code with Fractal's standard solution for this, but it also allows the most flexibility. For instance, with Fractal if I wanted to craft a URL like this:

`example.com/user?include=posts.comments`

I would get the relationships to work by putting one "include" function on the USER transformer to get the POSTS like this:

```
public function includePosts(User $user)
{
    return $this->collection($user->posts, new PostTransformer);
}
```

and one on the POSTS transformer to get the COMMENTS like this:

```
public function includeComments(Post $post)
{
    return $this->collection($post->comments, new CommentTransformer);
}
```

Is this a little boilerplate-y? Yeah, I guess so. But let's say users can also "like" posts on my site, and now I want to do a URL like this instead to get a user with their posts and each posts likes:

`example.com/user?include=posts.likes`

All I have to do is add another method on my POSTS transformer like this:

```
public function includeLikes(Post $post)
{
    return $this->collection($post->likes, new LikesTransformer);
}
```

And now that will work. It's boilerplate in a sense, but it also has a clear separation of concerns. Every single type of relationship you can request is defined in it's own place.

If you go the Filterable trait route, my fear is either that you'd be re-creating exactly what Fractal does by default above, which would be a waste of your time, or the solution would be less flexible. If we have a trait with a method that just gives me the "include" part of the URL and I have to then manually parse "posts.likes" or "post.comments" and load the relationship, it could get really messy.

And no problem! Happy to discuss this.

**Comment by flugger** [comment]
Hey again!

Sorry for the delay. I just pushed some changes to the package which should fix these problems.  First, I added a new configuration key: `load_relations_from_parameter`, which defaults to `'include'` and can be set to `null` to disable automatic relation loading from the GET parameter. I've also added the alternative route of parsing includes manually:

```php
return responder()->transform($user)->include('posts,comments:limit(5|1)')->respond();
```

Additionally, I've added a new property to the base transformer (and any new transformer created with `php artisan make:transformer`:

```php
protected $relations = ['*'];
```

As you can see, it defaults to `'*'`, which simply whitelists all relations. This means we have complete backwards compatibility, so I pushed the changes as a minor version `1.2.8`.

Oh yeah, and now you can create include methods in your transformer to filter your relations. The only difference from Fractal is that you call on `orders()` instead of `includeOrders()`. 

I've updated the documentation accordingly as well!

Here's the commit if you're interested in the implementation: https://github.com/flugger/laravel-responder/commit/183e5eb19cbc84828553cd92011a79ba8a6b8589

Let me know what you think :)

**Comment by imjohnbon** [comment]
Thanks for the update! Seems like a step in the right direction. I haven't dug too deeply into this but did try it out quickly last night. One question, it seems like whatever I add the the $relations variable on the transformer gets auto-loaded every single time I return that model.

For instance, if I have a `UserTransformer` and `protected $relations = [''posts'];`, **every time** I return a user I also get their posts. Is this intended functionality? What I was expecting was for the posts to only get returned when I add "posts" to the "include" param in the URL. If the relationship runs every single time, then I'm running an extra query every time I load a user even when I don't need their posts.

**Comment by flugger** [comment]
Ah, I see - that was indeed not intentional. I'll look into it

**Comment by flugger** [comment]
Hi again, pushed up a fix (`1.2.9`), let me know if you have any more issues with it :)

**Comment by computerfr33k** [comment]
I am having issues with the relations property as well, (using v1.2.9). It doesn't seem like it is applying the relations array properly. Here's the response I get:

```json
{
    "status": 200,
    "success": true,
    "data": [
        {
            "id": 1,
            "posts": [
                {
                    "id": 1
                }
            ],
            "comments": [
                {
                    "id": 1
                }
            ]
        }
    ]
}
```

Here is my code:

```php
Route::get('/api', function () {
    $users = User::with([ 'posts', 'comments' ]);

    return responder()->success($users);
});
```

```php
<?php

namespace App;

use App\Transformers\UserTransformer;
use Flugg\Responder\Contracts\Transformable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements Transformable
{

    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];


    /**
     * The path to the transformer class.
     *
     * @return string
     */
    public static function transformer()
    {
        return UserTransformer::class;
    }


    public function posts()
    {
        return $this->hasMany(Post::class);
    }


    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}
```

```php
<?php

namespace App\Transformers;

use App\User;
use Flugg\Responder\Transformer;

class UserTransformer extends Transformer
{

    /**
     * A list of all available relations.
     *
     * @var array
     */
    protected $relations = [ 'posts' ];


    /**
     * Transform the model data into a generic array.
     *
     * @param  User $user
     *
     * @return array
     */
    public function transform(User $user)
    {
        return [
            'id' => (int) $user->id
        ];
    }
}
```

**Comment by flugger** [comment]
Sorry, that was indeed a small mistake from my part. `1.2.10` should be good.

**Comment by computerfr33k** [comment]
1.2.10 Seems to be working for me

**Comment by imjohnbon** [comment]
2 questions regarding 1.2.10:

1) Am I correct in thinking that this is still different from Fractal in the sense that you need to manually pass your "include" parameter to your model in your controller?

2) I'm not sure if this is just my code, but when I load relationships via a model that has been route model binded, all of a sudden I get a list of all the models. For instance this:

```
    public function show(Request $request, User $user)
    {
        $user = $user->with($request->input('include', []));
        return responder()->transform($user);
    }
```

I get a list of ALL my users instead of just this user.

**Comment by flugger** [comment]
Hey again! 

1) No, it should be even simpler than that now - the package's service provider will now inject includes from the GET parameter "include" into the response builder automatically. You shouldn't need to do anything :) 

2) When calling `with()` on a model you are turning it into a query builder. If the responder receives a query builder it will call `get()` on it, which returns all users. You should instead use `load()`.

**Comment by imjohnbon** [comment]
Thanks for the reply! We're getting very close here.

1) The automatic injection you described doesn't work like that for me. For instance, when I call this URL:

`example.com/users/33?include=posts`

it works with this:

```
    public function show(Request $request, User $user)
    {
        $user = $user->load($request->input('include', []));
        return responder()->transform($user);
    }
```

but not with this:

```
    public function show(Request $request, User $user)
    {
        return responder()->transform($user);
    }
```

It seems like in my case, I need to do the "load" automatically.

2) Nested relationships don't seem to be working for me. For instance putting `posts.comments` in the "include" gives me the posts but not the comments.

**Comment by flugger** [comment]
Sorry about all the issues. I renamed the config name and forgot to change it in the service provider. Should all be good as of `1.2.13`, crossing my fingers there wont be more problems! I'll get around to write some more test scenarios for the new stuff this week.

Your point 3) should work fine. You can create a method named whatever in your transformers, and that will be called if the method exists, else it will just call `$model->relation`.

**Comment by imjohnbon** [comment]
Thanks man! No worries about the issues, I appreciate you being so open to suggestions. I will try the fix for #1 when I get home tonight.

Regarding #3, when I tried it last night I got an error (only for transformer relations that weren't also model relations). But let me try it again tonight to confirm. At the very least, I can get you the actual error message.

**Comment by imjohnbon** [comment]
Well, after trying this out tonight, everything works! Thank you again for being so open to my suggestions and quick to respond. With these additions, I really believe this package is the cleanest and most powerful fractal abstraction. Phenomenal job.

If I could make one final suggestion, I think it would be helpful to add more detail to the documentation about custom transformer relationship methods. Currently, the documentation has an example like this:

```
public function roles(User $user, ParamBag $paramBag)
{
    //
}
````

Normally in Fractal, you would fill out this method someway like this:

```
public function roles(User $user, ParamBag $paramBag)
{
    return $this->collection($user->roles, new RoleTransformer);
}
````

With this package, you do this:


```
public function roles(User $user, ParamBag $paramBag)
{
    return responder()->transform($user->roles)->getResource();
}
````

The important part there being, that in transformer relationship methods, you have to return an instance of a Fractal resource, which you can obtain with the "getResource()" method on your package. That's something I think most users could easily get stuck on.

**Thank you again.**

**Comment by flugger** [comment]
No worries, glad to be of help!

I admittely rushed the documentation a bit and will definitely improve it, so its on par with the rest of the documentation.

Btw, another thing is, you dont actually have to return a resource from the roles method, you may in fact return just the data: `return $user->roles;` and the package will wrap it in a resource automatically.

Thanks again for spending so much time on the issue, really appreciated! I will close this as it seems like all _issues_ are solved :)

**Comment by Hesesses** [comment]
Any ideas why the includes are not "automatically" working for me?
```
public function show(Request $request, $id)
    {
        $user = User::findOrFail($id);

        return Responder::success($user), 200); // doesnt include roles relationship

        return Responder::success($user::with('roles')), 200); // works
        return Responder::success($user::with($request->input('include', [])), 200); // works
    }

**Comment by flugger** [comment]
What version of the package are you on? And have you linked a transformer to your user model?

**Comment by Hesesses** [comment]
v1.2.17 and yes I have this on User Model
```
...implements Transformable

---

public static function transformer()
    {
        return UserTransformer::class;
    }

**Comment by flugger** [comment]
Hmm, and the `load_relations_from_parameter` configuration is left to the default 'include' value I suppose? The automatic including is performed in the service provider: https://github.com/flugger/laravel-responder/blob/master/src/ResponderServiceProvider.php#L123

Does the following work for you:

```
return Responder::transform($user)->include('roles')->respond(200);
```

This is basically how the automatic including works. You may also set a whitelist of which relations are allowed using the technique above using the `$relations` property in your transformer, however, that should default to `['*']`, which whitelists all relations.

**Comment by Hesesses** [comment]
Yes, its default 'include'.
That line works. 👍 

and actually its the only one of those I posted earlier which works. These lines includes the relationship, but for some reason they return all Users, not only the one with id=1
```
return Responder::success($user::with('roles')), 200); 
return Responder::success($user::with($request->input('include', [])), 200); 
```

This works perfectly, but doesnt look so nice:
```
return Responder::transform($user)->include($request->input('include', []))->respond(200);

**Comment by flugger** [comment]
When using `with()` you're getting a query builder, you want to load relations on a set model, so something like this should work:

```
return Responder::success($user->load('roles')), 200); 
````

However, with the `load_relations_from_parameter` set, you shouldn't need to explicitly load relations. Could you try adding the following code on line 123 in `Flugg\Responder\ResponderServiceProvider`:

```
dd($this->app[Request::class]->input($parameter, []));
```

Does that output `'roles'`?

**Comment by Hesesses** [comment]
It outputs `[]`

**Comment by flugger** [comment]
Hmm, that's the problem then. Does `dd($parameter);` output `'include'`? And what do you get when you do `dd($this->app[Request::class]->all());`?

**Comment by Hesesses** [comment]
`dd($parameter) = "include"`
and
`dd($this->app[Request::class]->all()) = []`
