### ISSUE TITLE
Can I use this to show custom arrays?

### ISSUE THREAD

**Issue by Krato** [flugger/laravel-responder#17]
Hi, is possible to work with this awesome package to get a custom created array or Collection, no just Eloquent?

Thanks

**Comment by flugger** [comment]
Hey! Non-Eloquent data should be passed as meta data to the responder at the moment. You could do:

```php
return responder()->success(null, $array);
```

**Comment by Krato** [comment]
Yes thank you. I can see that on documentation. 😄
