### ISSUE TITLE
Php 5.6

### ISSUE THREAD

**Issue by Krato** [flugger/laravel-responder#18]
Hi, we are using PHP 5.6 in our server.

There is some package like this to work without php7?

Thanks!

**Comment by flugger** [comment]
Hi Krato! The package uses PHP7 features quite extensively. While it might be a bit premature to drop 5.6 support, I believe in pushing the world forward, and PHP7 is such a huge performance boost. If you're not able to upgrade to PHP7, you can alternatively use [spatie/laravel-fractal](https://github.com/spatie/laravel-fractal) which seems to have support for 5.6 :)

**Comment by Krato** [comment]
Ok.

Thanks so much for your fast reply 😃
