### ISSUE TITLE
Exclude Relationship

### ISSUE THREAD

**Issue by computerfr33k** [flugger/laravel-responder#19]
Is there currently a way to exclude a relationship from being included in the response.

**Comment by flugger** [comment]
No, not explicitly. I do want to adopt something similar to Fractals `$availableIncludes` to the transformers. At the moment it should only include what is eager loaded into the model when passed to the responder, so you can remove whatever relation you don't want included manually.

**Comment by flugger** [comment]
Hey again!

I just updated the package with a minor version, which includes some improvements to relations. You now have access to a `$relations` property in your transformers. Detailed info has been added to the docs. Thanks for reporting the issue :)

**Comment by computerfr33k** [comment]
Awesome, thanks!

On October 30, 2016 6:10:10 AM CDT, "Alexander Tømmerås" <notifications@github.com> wrote:
>Hey again!
>
>I just updated the package with a minor version, which includes some
>improvements to relations. You now have access to a `$relations`
>property in your transformers. Detailed info has been added to the
>docs. Thanks for reporting the issue :) 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/flugger/laravel-responder/issues/19#issuecomment-257144931

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
