### ISSUE TITLE
Laravel 5.1 vendor:publish Error

### ISSUE THREAD

**Issue by computerfr33k** [flugger/laravel-responder#21]
When using Laravel 5.1 and running `php artisan vendor:publish` I get the following error: `Call to undefined function Flugg\Responder\resource_path()`

**Comment by flugger** [comment]
Oh, I just checked and apparently `resource_path()` was introduced in Laravel 5.2 - I guess the best option would be to change all of them to `app_path('resources/...')`.

Thanks for finding all them bugs :)

**Comment by flugger** [comment]
This should be fixed aswell from `1.2.12`. Thanks again!
