### ISSUE TITLE
Status code not included anymore

### ISSUE THREAD

**Issue by andcl85** [flugger/laravel-responder#34]
I have noticed that executing `composer update` command to latest release, v1.2.20, the status code of api calls is not included even when `'include_status_code' => true` in `responder.php` config file...

**Comment by andcl85** [comment]
In src/ResponderServiceProvider.php, you have:
`return $builder->setIncludeSuccessFlag($app->config->get('responder.include_success_flag'));            return $builder->setIncludeStatusCode($app->config->get('responder.include_status_code'));`

It obviously executes only the first `return` statement, and then exits, so the `include_status_code` option is never used...

**Comment by andcl85** [comment]
I have written a PR that fixes this issue.

**Comment by flugger** [comment]
Seems like an issue introduced in the last pull request, thanks for spotting it! I'll get the pull request merged and tag a release.
