### ISSUE TITLE
You can only transform data containing Eloquent models.

### ISSUE THREAD

**Issue by adam-devapp** [flugger/laravel-responder#36]
More a feature request than a bug. Any chance of supporting collections in the future, instead of just Eloquent?

The API I'm writing enables filters some queries on collections, which require the query to have been run first.

**Comment by flugger** [comment]
Hi! Im working on a v2 of the package which will indeed allow transforming raw arrays/collections. The new version should be released within the month :)

**Comment by adam-devapp** [comment]
Fantastic. Happy to test once ready.

**Comment by flugger** [comment]
Have had limited time to work on the package due to an upcoming deadline at work, so sorry to everybody waiting patiently for version 2. I'll get more time for it pretty soon and will update this thread once it's released.

**Comment by Smashmint** [comment]
Waiting on it here as well, I would like to add custom parameters to a collection transformer besides meta data as well.

**Comment by cberio** [comment]
seems its late but works find to me.

in my case I had to write raw sql query.
```php
public function index()
{
    // $sql = some select statement.
    // $params = array(some params).
    $result = DB::select($sql, $params);

    // and I made view-model for query result and fill with it
    $nowItsModel = CustomViewModel::hydrate($result);
    return responder()->transform($nowItsModel, function($data) {
        return [
            // you can specify field which you want use and types
            'integer_field' => (int) $data->id,
            'string_field' => $data->name
        ];
    });
}
``
hope it helps!

**Comment by flugger** [comment]
Hey folks! Big news, version 2.0 is officially released! 🎉

It brings loads of new features, including the possibility of transforming non-models! Be sure to check the changelog for everything new.
