### ISSUE TITLE
How to Pass the Resource Key

### ISSUE THREAD

**Issue by Warlock-developer** [flugger/laravel-responder#38]
Hi, I think this is a very good packet, I am implementing it but i have a question.
 
How to pass the resource key into the Respond.
Fractal do this like this.
// Important, notice the Resource Key in the third parameter:
$resource = new Item($book, new JsonApiBookTransformer(), 'books');
books is the resouce key but I do not how to do it in laravel-responder.

thanks

**Comment by flugger** [comment]
Hi! When using the short syntax form (responder->success()) it's not possible to specify resource key (it defaults to table name of the model). However, you may use the more verbose syntax when you want more options: responder()->transform($book, new JsonApiBookTranformer, 'books')->respond().

**Comment by Warlock-developer** [comment]
Ok. I am doing this.
$book = Book::all();
return responder()->transform($book, new JsonApiBookTranformer, 'books')
            ->serializer( new JsonApiSerializer())->respond();

but the result no working.

"success": true,
  "status": 200,
  "data": [
    {
      "type": "library", --> this should be books
      "id": "8049",
      "attributes": {
        "name": "Example",
      },
      "links": {
        "self": "http://localhost/api/v1/library/8049"
      }
    },


thanks for your help

**Comment by Warlock-developer** [comment]
Hello, I think that I fix it,  in the \Flugg\Responder I add  the variable string $resourceKey = null, this variable was not present

public function transform($data = null, $transformer = null, string $resourceKey = null)

**Comment by flugger** [comment]
Oh, that seems to be missing indeed. Thanks! I'll release a fix for it soon. Instead of specifying the resource key every time, you may also implement a getResourceKey in your model returning the wanted key as a string.
