### ISSUE TITLE
Throwing same exception

### ISSUE THREAD

**Issue by F3rmiParad0x** [flugger/laravel-responder#39]
Hi,

I have a question about error handling. I have comes across this when setting the Laravel `App\Exceptions\Handler` to use `Flugg\Responder\Exceptions\Handler as ExceptionHandler`. It looks like lines 78-80 of the file  `laravel-responder/src/Traits/HandlesApiErrors.php` catches and throws the same error. Should the newly thrown error be an instance of `Flugg\Responder\Exceptions\Http\RelationNotFoundException` instead of  `Illuminate\Database\Eloquent\RelationNotFoundException`?

```php
/**
     * Transform an Eloquent exception into an API exception.
     *
     * @param  Exception $exception
     * @return void
     * @throws ResourceNotFoundException
     * @throws RelationNotFoundException
     */
    protected function transformEloquentException(Exception $exception)
    {
        if ($exception instanceof ModelNotFoundException) {
            throw new ResourceNotFoundException();
        }
        if ($exception instanceof RelationNotFoundException) {
            throw new RelationNotFoundException();
        }
    }
```

One change could be:

```php

/**
     * Transform an Eloquent exception into an API exception.
     *
     * @param  Exception $exception
     * @return void
     * @throws ResourceNotFoundException
     * @throws RelationNotFoundException
     */
    protected function transformEloquentException(Exception $exception)
    {
        if ($exception instanceof ModelNotFoundException) {
            throw new ResourceNotFoundException();
        }
        if ($exception instanceof RelationNotFoundException) {
            throw new \Flugg\Responder\Exceptions\Http\RelationNotFoundException();
        }
    }
```
Am I overlooking anything with this proposed change?

Thanks,

**Comment by flugger** [comment]
Hi, 

You're right, your second example should fix it. Would you mind making a pull request out of it? If not, I'll try to get it fixed over the weekend. Thanks for the heads up :)
