### ISSUE TITLE
Support for polymorphic relations

### ISSUE THREAD

**Issue by pascalschwientek** [flugger/laravel-responder#4]
Hey,

I started running into an issue with the responser and polymorphic relations.

```php
/**
     * Call Include Method.
     *
     * @param  Scope  $scope
     * @param  string $includeName
     * @param  mixed  $data
     * @return \League\Fractal\Resource\ResourceInterface|bool
     * @throws \Exception
     */
    protected function callIncludeMethod( Scope $scope, $includeName, $data )
    {
        if ( ! $data instanceof Transformable || ! $data->relationLoaded( $includeName ) ) {
            return false;
        }

        $data = $data->$includeName;

        return app( Responder::class )->transform( $data );
    }
```

The problem is that it just transforms `$data` after accessing the `$includeName` property.
With polymorphic relations a 'pivot' property will be access which return a `MorphPivot` class.
This class can not be transformed and an exception will be thrown.

An easy fix would be to check after `$data = $data->$includeName;` if `$data` is an instance of `MorphPivot`. But I don't think this would be the best fix. Maybe there is a better way to handle those cases and other "pivot" cases in a better way.
If there is no transformer for a possible include, don't include it, instead of throwing an exception?

**Comment by flugger** [comment]
Hi!

I'll have a look at it right away and see if I can work out a clever way of handling it. Thanks for reporting, I'll keep you posted :)

**Comment by flugger** [comment]
A bit more work than expected, but it should work with both pivot tables and polymorphic pivot tables now. Added a new section in the documentation to explain it: [Transforming Pivots](https://github.com/flugger/laravel-responder/tree/master#transforming-pivots).

**Comment by pascalschwientek** [comment]
Awesome, thanks for the quick fix. I just updated and its working for me!
