### ISSUE TITLE
transformPivot

### ISSUE THREAD

**Issue by mitjarobic** [flugger/laravel-responder#41]
Could you provide an example of how to use the transformPivot method?

**Comment by flugger** [comment]
Hi! Yes, sorry about the lack of documentation. When you transform a model with a belongs to many relation loaded, the corresponding Pivot model will be transformed if a `transformPivot` method exists. The pivot table data will not be included if no `transformPivot` method is defined. You may optionally transform the pivot data directly in the `transform` method using `'foo_id' => $model->pivot->foo_id`. The data transformed through the `transformPivot` method will be appended inside a `pivot` field in your final response.

I will release a new revision of the documentation soon clearing up this stuff. Thanks and let me know if you're still having issues.

**Comment by mitjarobic** [comment]
I have done it in this way, like you said: 'foo_id' => $model->pivot->foo_id. 

The reason i asked the question is that the method transformPivot does not fire.

**Comment by flugger** [comment]
Hey, with the release of version 2, the `transformPivot` function has been removed in favor of just calling `$model->pivot->foo_id`. I will close this, thanks for the issue!
