### ISSUE TITLE
[Idea] Register Transformers like Policies

### ISSUE THREAD

**Issue by faustbrian** [flugger/laravel-responder#43]
I recently was playing around with the package and thought Models could be cleaned up a bit by registering transformers in the same way as policies are registered.

**TransformerServiceProvider**
```
<?php

namespace App\Providers;

use App\Models;
use App\Transformers;
use Flugg\Responder\TransformerServiceProvider as ServiceProvider;

class TransformerServiceProvider extends ServiceProvider
{
    /**
     * The transformer mappings for the application.
     *
     * @var array
     */
    protected $transformers = [
        Models\Post::class => Transformers\PostTransformer::class,
        Models\Picture::class => Transformers\PictureTransformer::class,
        Models\User::class => Transformers\UserTransformer::class,
    ];

    /**
     * Register any transformer services.
     */
    public function boot()
    {
        $this->registerTransformers();
    }
}
```

**Old Model**
```
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Flugg\Responder\Contracts\Transformable;

class User extends Authenticatable implements Transformable
{
    public static function transformer()
    {
        return \App\Transformers\UserTransformer::class;
    }
}
```

**New Model __(No need for interface or transform method)__**
```
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    // ...
}
```

The interface and transform method would no longer be required since we could just check if the model has a transformer bound to it.

Would do you think about this approach?

**Comment by flugger** [comment]
Hey Brian! I like the idea and it was something I considered when I first created the package. The only downside I can see is that people would have to manually create the service provider and copy/paste the boilerplate from the documentation. Not sure what I like the most, but it could potentially be an alternative way of registering transformers.

**Comment by faustbrian** [comment]
Well currently you need to add a transformer method to each provider so I think creating a service provider once and adding a line there is the same amount of work, just keeps things a bit cleaner I think.

**Comment by flugger** [comment]
I agree with you that it's easier, but we would lose the possibility to add simple closure transformers in the models:

```
public static function transformer() {
    return function($model) { return [ ... ]; }
}
```

I'll give this some more thought, but do appreciate the idea

**Comment by faustbrian** [comment]
You could still keep both options available I would assume to be backwards compatible and allow more control, it would just make things cleaner if you just have a simple transformer class for 99% of your models.

**Comment by faustbrian** [comment]
@flugger will the v2 get a release tag soon? About to deploy an application and could clean it up a bit with the new TransformerManager.

**Comment by flugger** [comment]
Hey! Yeah, Just fixing the last bugs and increasing test coverage slightly, but should be out next week is my bet.

**Comment by faustbrian** [comment]
Will close this issue then. Thanks.
