### ISSUE TITLE
Abstract methods must be declared or implement

### ISSUE THREAD

**Issue by nasyrov** [flugger/laravel-responder#44]
Hi @flugger,

Thanks for a fantastic package!

Me using it with Laravel 5.4 and in my base test case, I'm pulling your helper trait `MakesApiRequests`. However, that gives me the error:
```
[Symfony\Component\Debug\Exception\FatalErrorException]
  Class AgentsCreateTest contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (TestCase::seeJsonSubset, T
  estCase::decodeResponseJson)
```

Is that something I should implement myself?

Thanks,
Evgenii

**Comment by flugger** [comment]
Hi!

Thanks for the good words. Laravel 5.4 changed the testing API slightly. They released a package to keep backwards compatibility: https://github.com/laravel/browser-kit-testing 

I'm working on a v2 which will include some improvements to this, but in the mean time you will need to bring in the package above for the trait to work.

**Comment by nasyrov** [comment]
Hi @flugger,

Thanks for your reply, I'll give it a try!
