### ISSUE TITLE
Call to undefined function Flugg\Responder\request()

### ISSUE THREAD

**Issue by nasyrov** [flugger/laravel-responder#45]
Hi @flugger,

Me again, trying to implement simple pagination and getting the error:
![screen shot 2017-06-18 at 9 00 06 pm](https://user-images.githubusercontent.com/1330477/27263800-240b9ee0-5469-11e7-9099-6f17b6c32920.png)

My code:
``` php
public function index()
{
    return responder()->success(Agent::paginate(10));
}
```

Any thoughts how I can fix that?

Cheers,
Evgenii

**Comment by flugger** [comment]
Hey again :)

Are you using Lumen by any chance?

**Comment by nasyrov** [comment]
Hi @flugger,

Yep

**Comment by flugger** [comment]
Sorry about the issue and thanks for reporting it - it's related to a recent change where the `request()` helper method was used internally. However, that method is not included with Lumen.

I made a change now which should have fixed it, so please try to run `composer update flugger/laravel-responder` and see if it solves it.

**Comment by nasyrov** [comment]
Hi @flugger,

Much appreciate for a quick update!
It works like a charm!

**Comment by nasyrov** [comment]
Hi @flugger,

Off-topic: you should put some kind of donate or "buy me a beer" button ;)

**Comment by flugger** [comment]
Haha, thanks! I'll consider it, but as long as my package helps developers across the world build cool stuff, I'm happy :)
