### ISSUE TITLE
Customize error format (Serializer for Errors)

### ISSUE THREAD

**Issue by ductiletoaster** [flugger/laravel-responder#47]
One issue I have had is that my team is responsible for integrating with some services that use a slightly different error response body. We would like to maintain a standard across all of our services and so having a way to easily define the format of the ErrorResponse would be amazing.

**Comment by flugger** [comment]
You might be happy to know version 2, being released within days, includes a concept for error serializers for customizing it exactly the way you want :)

**Comment by ductiletoaster** [comment]
Nice! Will this newest version be compatible with the same versions of laravel/lumen? Also anyway we can checkout the dev release prior to official release? I had made contributions in the past and I'd love to continue to help where I can! :)

**Comment by flugger** [comment]
Yeah, the plan is to keep the same version requirements. I started a new rewrite after the current dev branch was created, so that's not currently up to date. However, I can push it all up on a new branch if you want to take a look. It's not quite ready to be used in production yet though, but it's almost there! All feedback and help is definitely highly appreciated :)

**Comment by ductiletoaster** [comment]
That sounds great! Going to close this ticket unless you want to keep it open until release?

**Comment by flugger** [comment]
Made a new "v2" branch located here: https://github.com/flugger/laravel-responder/tree/v2

The documentation has also been rewritten (but it's not complete). Lemme know what you think!

And sure, let's keep it open until the version is released.

**Comment by ductiletoaster** [comment]
Awesome! Took a quick glimpse and it all looks great! Would you like me to do Pull Requests for feedback? or just comment back here?

**Comment by flugger** [comment]
Either is fine really! If you have certain things you want to discuss in more detail it might be easier to use another platform. Are you a member of the Larachat Slack channel by any chance?

**Comment by ductiletoaster** [comment]
Just join under `ductiletoaster`

**Comment by flugger** [comment]
Version 2 has been released and introduces the concept of error serializers.
