### ISSUE TITLE
questions about loading relations via query string.

### ISSUE THREAD

**Issue by cberio** [flugger/laravel-responder#48]
first of all, thanks for your works.

is this intended result that lazy-loaded when load relations via query string?
```php
// api/users?include=post
public function index(Request $request)
{
    $query = User::paginate();

    // this will lazy-loaded
    return responder()->success($query);

    // this will eager-loaded
    return responder()->success($query->load($request->include));
}
```
or am I missing something?

**Comment by flugger** [comment]
Hey! Yes, unfortunately, the current release wont eager load the data automatically for you. However, the new version being released pretty soon, will.

**Comment by cberio** [comment]
great 👍
thanks for reply.

**Comment by flugger** [comment]
The new version is released and it has automatic eager loading!
