### ISSUE TITLE
any roadmap to add Authentication like JWT?

### ISSUE THREAD

**Issue by ghprod** [flugger/laravel-responder#5]
Auth feature would be very nice :+1:

**Comment by flugger** [comment]
Hi, thanks for your issue!

The package already integrates nicely with packages like [tymondesigns/jwt-auth](https://github.com/tymondesigns/jwt-auth). Implementing an entire JWT auth solution is a bit outside the responsibility area I had in mind for the package. However, I'm open for ideas if there's anything in particular you feel is missing from the JWT package above?

**Comment by ghprod** [comment]
Hi @flugger 

Yes, we can use package from Tymon :)

Thanks for your package :+1:
