### ISSUE TITLE
[Question] Error handling

### ISSUE THREAD

**Issue by nasyrov** [flugger/laravel-responder#51]
Hi @flugger,

I'm working on Lumen application and I was wondering if I can completely disable `Whoops, looks like something went wrong.` message and always receive the output like:

``` json
{
    "success": false,
    "status": 500,
    "error": {
        "code": null,
        "message": null
    }
}
```

I followed your guide and included the trait `HandlesApiErrors`, as well as added `$this->transformException($exception);` to my `render` method.

Cheers,
Evgenii

**Comment by flugger** [comment]
Hey Evgenii :)

Have you copy pasted all the lines from the `render` method of the package's exception handler? Including:

```php
        if ($exception instanceof ApiException) {
            return $this->renderApiError($exception);
        }
```

**Comment by nasyrov** [comment]
Hi @flugger,

Thanks for the reply!
Yes I did, and this is my full method code:

``` php
    public function render($request, Exception $exception)
    {
        // Uncomment to debug travis-ci output
        // throw $exception;
        $this->transformException($exception);
        if ($exception instanceof ApiException) {
            return $this->renderApiError($exception);
        }
        return parent::render($request, $exception);
    }
```

**Comment by flugger** [comment]
Hmm, that's weird. I assume you've imported the full `Flugg\Responder\Exceptions\Http\ApiException` file in the top?

What errors are you getting if you enable debug mode?

**Comment by nasyrov** [comment]
@flugger, my intent is to get rid of the Woops page and make sure all the responses either success or error return in JSON format.

**Comment by flugger** [comment]
Yes, correct. Thats what the code above should fix. Perhaps Lumen throws a different exception on page not found than Laravel. I'll do some investigation and get back to you!

**Comment by nasyrov** [comment]
In the second example, my application throws a standard UnexpectedValueException. Maybe I should re-catch in the handler?

**Comment by flugger** [comment]
If your `UnexpectedValueException` extends `ApiException` it should automatically be caught with the code in your handler. I just created a Lumen application and did some testing and realised, there is no default exception transformer for _page not found_ errors. I definitely think it should be included out of the box and will look into getting it into the v2 release. As a workaround, you can catch the 404 errors manually in the `render` method:

```php 
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

if ($exception instanceof NotFoundHttpException) {
            return responder()->error('page_not_found', 404, 'The page you are looking for could not be found.');
        }
```

**Comment by flugger** [comment]
Did you find a solution?

I also just realised `UnexpectedValueException` is a standard PHP exception, so that would also need to be caught and handled, like the `NotFoundHttpException` above. Generally speaking, it might be a good idea to make exceptions that extend the `ApiException` abstract class and throw them instead. That way you will get the automatic converting to error responses without having to intercept them yourself.

**Comment by nasyrov** [comment]
Hi @flugger,

or maybe make a mapping like so:

``` php
$mapping = [
    UnexpectedValueException::class => NotFoundHttpException::class
];
```

**Comment by flugger** [comment]
Yeah, that's definitely a good idea and something I've considered in the past, but stuff like the `ValidationFailedException` expects a validator argument which is hard to pull off with the array version.

**Comment by flugger** [comment]
Hmm, what about allowing closures, so you can do this:

```php
$mappings = [
    UnexpectedValueException::class => NotFoundHttpException::class,
    ValidationException::class => function ($exception) {
        return new ValidationFailedException($exception->validator);
    },
];
```

**Comment by flugger** [comment]
I've been playing around with it some more and so far this will be possible in v2:

```php
    public function render($request, Exception $exception)
    {
        $this->convert(ValidationException::class, function($exception) {
            throw new ValidationFailedException($exception->validator);
        });
        
        $this->convert(UnexpectedValueException::class, NotFoundHttpException::class);
            
        $this->convertLaravelException($exception);

        if ($exception instanceof ApiException) {
            return $this->renderErrorResponse($exception);
        }

        return parent::render($request, $exception);
    }
```

**Comment by nasyrov** [comment]
Hi @flugger,

That looks good to me, I thought about my problem as well, probably the best thing to do in my case is to wrap the functionality with `try ... catch`.

``` php
try {
    if (some critical stuff)
        throw new UnexpectedValueException;
} catch(UnexpectedValueException $e) {
    return responder()->error('oops_1');
} catch(ValidationException $e) {
    return responder()->error('oops_2');
}
```

The thing is, some of these exceptions could be thrown by 3rd party extensions that I installed via Composer, so I cannot update them and extend from `ApiException`.

**Comment by flugger** [comment]
Yeah, thats usually how I solve it in my apps :) You can also of course also catch the exceptions and rethrow your own versions that extend `ApiException`.

**Comment by nasyrov** [comment]
Alright, thanks a lot! I'm closing this for now ...
