### ISSUE TITLE
Class Translator does not exist

### ISSUE THREAD

**Issue by abhimanyu003** [flugger/laravel-responder#57]
Firstly great package and awesome work.

I'm using laravel 5.3 the error I'm getting is
```
Class Illuminate\\Contracts\\Translation\\Translator does not exist
```
As I can see it's been used at 2 places.

**Question**

In response, there is always `status` and `success` key added no matter what Serializer i'm using.
What is the best way to not include these two key?

```
    "status": 200,
    "success": true,
```

**Comment by flugger** [comment]
I see the translator interface was added recently, I will get that changed with the actual implementation which has been around for ages. Thanks!

The `status` and `success` fields are added by the response decorators. You can disable them in the configuration file. More information here: https://github.com/flugger/laravel-responder#decorating-response

**Comment by flugger** [comment]
`2.0.4` has been released fixing the translator bug.
