### ISSUE TITLE
keep getting "Data must only contain models implementing the Transformable contract." error

### ISSUE THREAD

**Issue by sullysheperd** [flugger/laravel-responder#6]
Hi
I have implemented the Transformable contract (at least that's what I think!) yet I keep getting this error. I'm using Laravel 5.2 and this is how I have implemented it:

In my User.php (model) I have added these at the top:

```
use App\Transformers\UserTransformer;
use Illuminate\Database\Eloquent\Model;
use Flugg\Responder\Contracts\Transformable;
```

and these in the class:

```
/**
     * The path to the transformer class.
     *
     * @return string|null
     */
    public static function transformer()
    {
        return UserTransformer::class;
    }
```

And I have created a UserTransformer with these codes in it:

```
namespace App\Transformers;

use App\User;
use Flugg\Responder\Transformer;

class UserTransformer extends Transformer
{
    /**
     * Transform the model data into a generic array.
     *
     * @param  User $user
     * @return array
     */
    public function transform(User $user):array
    {
        return [
            'id' => (int) $user->id,
            'email'    => $user->email,
            'username' => $user->username
        ];
    }
}
```

Yet when I try to use it by this test method(in my UserController file):

```
public function tests(){
      $users = User::all();
      return Responder::success( $users );
    }
```

I get this error:
Data must only contain models implementing the Transformable contract.

Am I missing something here?
Thanks

**Comment by nlocascio** [comment]
Did you implement the Transformable interface on your User class?

User.php:

```php
class User extends Model implements Transformable {
```

**Comment by flugger** [comment]
Hi, everything seems to be right from your code examples above, so I would need some more information to go on. Do you have the full stack trace of the error? 

And could you try to do a `dd($users)` right before your `return Responder::success( $users );` - this might be related to the issue @nlocascio opened about empty collections. Do you have a user model in the database?

**Comment by flugger** [comment]
A fix for empty collections has been pushed, do you still encounter the same problems after updating your dependencies @sullysheperd?

**Comment by sullysheperd** [comment]
@nlocascio your suggestion fixed it! 
This was the code beginning my User class:

```
class User extends Authenticatable {
// the rest
```

Turns out I should have implemented Transformable into it using this syntax:

```
class User extends Authenticatable implements Transformable{
// the rest
```

Everything works fine now. Thank you @flugger for your great package. One quick question though: 
Days before I found your package I watched few of Jeffrey's videos about api:
https://laracasts.com/series/incremental-api-development
And I see you have implemented the same. Can I ask if you have watched the series and implemented the same codes(with more details I guess)? I'm only asking this because I'm a big fan of Jeffrey's work and I need the api to be perfect in my new project. Once again thank you for your great package ;)

**Comment by flugger** [comment]
Yeah, I've watched the videos, some good introductory stuff for API development. This package solves many of the same problems as Jeff does in the series, and I've definitely been inspired by the videos over at Laracasts over the years :)

I'm glad you've chosen this packageI - I hope it helps you build the perfect API!
