### ISSUE TITLE
ValidationFailedException error structure changed.

### ISSUE THREAD

**Issue by cberio** [flugger/laravel-responder#60]
first of all, thanks for your efforts. 👍 

after migrate from 1.* to 2.*, I found a undocumented changes. 
I just leave this issue for others.

2.*
https://github.com/flugger/laravel-responder/blob/77c90a6991570d96377ee87b7c54a2e676369d15/src/Exceptions/Http/ValidationFailedException.php#L55-L58
```json
{
    "status": 422,
    "success": false,
    "error": {
        "0": {
            "some_fields": [
                "messages"
            ]
        },
        "code": "validation_failed",
        "message": "The given data failed to pass validation."
    }
}
```
1.*
https://github.com/flugger/laravel-responder/blob/f8044cafde230602d35da1dcc5e609e3c04aeeab/src/Exceptions/Http/ValidationFailedException.php#L54-L57
```json
{
    "success": false,
    "status": 422,
    "error": {
        "code": "validation_failed",
        "message": "The given data failed to pass validation.",
        "fields": {
            "some_fields": [
                "messages"
            ]
        }
    }
}
```

**Comment by flugger** [comment]
Hey! Appreciate the kind words and thanks for reporting the issue. This is not the expected behaviour and the missing `'fields'` key must have slipped out accidentally. I will get it fixed and tag a release!

**Comment by flugger** [comment]
A `2.0.5` version has been tagged which should add the `fields` key again. Please let me know if you meet more problems :)
