### ISSUE TITLE
problem when loading several relations through query parameter

### ISSUE THREAD

**Issue by neokike** [flugger/laravel-responder#62]
When trying to load several relationships through query parameter via with i always get a call to undefined relationships Exception.

it appears that the relations came as a string and they are not converted to array.

**Example**: if i make a request like the following

```GET users?with=roles,permissions```

the response that i get is:

```Response: Call to undefined relationship [roles,permissions] on model [App//User]```

PD: When i load a single relation via with param the request have no problem at all

**Comment by flugger** [comment]
Hey, thanks for reporting! This should now be fixed, also tagged a `2.0.6` release.
