### ISSUE TITLE
Incompatible API Middleware Exception

### ISSUE THREAD

**Issue by kevmt** [flugger/laravel-responder#64]
Hi,

I seem to have having issues on this one.  I am on `laravel/framework 5.4.*`

```
Type error: Argument 2 passed to Barryvdh\\Cors\\HandleCors::addHeaders() 
must be an instance of Symfony\\Component\\HttpFoundation\\Response, instance of
Flugg\\Responder\\Http\\Responses\\ErrorResponseBuilder given
```

Incase you say HandleCors or third parties concern, see:

```
Type error: Argument 1 passed to Illuminate\\Routing\\Middleware\\ThrottleRequests::addHeaders()
must be an instance of Symfony\\Component\\HttpFoundation\\Response, instance of
Flugg\\Responder\\Http\\Responses\\ErrorResponseBuilder given
```

**Comment by flugger** [comment]
Hey, I'm guessing you're returning `responder()->error(...)` from your controller? Try to append `respond` behind it to convert it to a `JsonResponse` (which inherits from `Symfony\Component\HttpFoundation\Response` and should solve the middleware issue from the other package):

```php
return responder()->error(...)->respond();
```

Let me know if this helps

**Comment by kevmt** [comment]
Hi, actually it is what I am returning. This is my Override Exception Handler Class; loaded via
`$this->app->singleton(ExceptionHandler::class, ApiExceptionHandler::class)` and the class is

```
/**
 * Class ApiExceptionHandler
 * @package Modules\Api\Exceptions
 */
class ApiExceptionHandler extends ExceptionHandler
{
    /**
     * We don't use the `responder.exceptions`
     *
     * @inheritdoc
     */
    public function render($request, \Exception $exception)
    {
        // Only checks for api.<domain> or <domain>/api/
        if (isApiCall($request)) {
            $code = 500;

            if ($exception instanceof HttpException) {
                $code = ($code = $exception->getStatusCode()) === 404 ? 400 : $code;
            } elseif ($exception instanceof AuthenticationException) {
                $code = 401;
            }

            if (empty($message = $exception->getMessage())) {
                $message = Response::$statusTexts[$code];
            }

            $errClassName = strtolower(snake_case(str_replace('HttpException', '', class_basename($exception))));
            $errorCode = 'api_' . (empty($errClassName) ? 'unknown_error' : $errClassName);

            return responder()->error($errorCode, $message)->respond($code);
        }

        return parent::render($request, $exception);
    }
}
```

**Comment by flugger** [comment]
Hmm, I only manage to replicate the error when not using `respond`. The `respond` should convert the `ErrorResponseBuilder` to a `JsonResponse`, are you certain you're not calling `responder()->error()` somewhere else?

**Comment by kevmt** [comment]
In my api route, I only have:

```
Route::get('/', function() {
    return responder()->success([
        'app' => config('app.name'),
        'domain' => request()->getHost(),
        'version' => 1
    ]);
});

Route::resource('ping', 'PingController');
```

and my ApiController

```
/**
 * Class ApiController
 * @package Modules\Api\Http\Controllers
 */
class ApiController extends Controller
{
    use MakesResponses;

    /**
     * @inheritdoc
     * @throws BadRequestHttpException
     */
    public function __call($method, $parameters)
    {
        throw new BadRequestHttpException();
    }
}
```

lastly my PingController

```
/**
 * Class PingController
 * @package Modules\Common\Http\Controllers
 */
class PingController extends ApiController
{
    public function index()
    {
        return $this->success('pong');
    }
}
```

that is only it..

**Comment by kevmt** [comment]
Weird thing is, sometimes it throws that above error, sometimes it pushes through; it triggers that error when I refresh or call the route rapidly.

**Comment by flugger** [comment]
This seems very weird. I've tried to refresh a hundred times, still not able to recreate the error :(  Could you paste the full stack trace perhaps?

**Comment by flugger** [comment]
@kevmt Any updates on this?

**Comment by kevmt** [comment]
@flugger Hi, Yes.. you are correct I am calling the `responder()->error(...)` somewhere, I forgot that I also added an override to the Throttle Middleware and worst, it was using the version 1.0 `responder()->error($errorCode, ..., ...)`.  I am very sorry about this.

Library works as expected.

**Comment by flugger** [comment]
Ahh, that explains why it would only fail sometimes. And absolutely no problem, just glad everything works as expected :)
