### ISSUE TITLE
Cannot make non static method Flugg\Responder\Contracts\Transformable::transformer() static in class App\User

### ISSUE THREAD

**Issue by Hesesses** [flugger/laravel-responder#65]
Hi,

I'm upgrading the old versio to 2.0. I have installed the new version, removed the old config file etc..

Now i'm trying to run phpunit but before it executes any tests i get this error:
`Fatal error: Cannot make non static method Flugg\Responder\Contracts\Transformable::transformer() static in class App\User ... on line 13`

Line 13 is `class User extends Authenticatable implements Transformable`

Any ideas?

**Comment by flugger** [comment]
Hey! In version 2, the `transformer` method of the `Transformable` contract has changed from static to non-static. I guess you still have a static method in your User model?

**Comment by Hesesses** [comment]
```
public static function transformer()
    {
        return UserTransformer::class;
    }
```
Yep, thanks 🙈

**Comment by flugger** [comment]
Glad you got it sorted out 😀 Let me know if you encounter more problems with the upgrade!

**Comment by Hesesses** [comment]
Just wanted to let everyone know that migrating from old version to 2.0 was super easy, search & replace is your best friend 👍
