### ISSUE TITLE
Handler not converting 404 in Laravel 5.5

### ISSUE THREAD

**Issue by dragonfire1119** [flugger/laravel-responder#66]
It shows JSON for just regular browser requests. It should show JSON on api requests & for HTTP browser requests the regular 404 view.

If I use https://github.com/flugger/laravel-responder#option-2-use-convertsexceptions-trait it returns the 404 view but not a 404 JSON response just a error with no message.

Right now i'm just using this with Option 2:

```
if($request->wantsJson()) {
       $this->convertDefaultException($exception);
    
       if ($exception instanceof HttpException) {
             return $this->renderResponse($exception);
       }
}
```

**Comment by flugger** [comment]
Hi - I agree the handler should check for this. Just tagged `v2.0.9` which makes the change. I've also added a little paragraph about it to the `Option 2` section of the handler docs.
