### ISSUE TITLE
BindingResolutionException

### ISSUE THREAD

**Issue by jmurphy45** [flugger/laravel-responder#67]
I am getting this error in lumen when I try to use this library. Not if this is a bug to I am doing something wrong. 

    BindingResolutionException
    Target [Illuminate\Contracts\Translation\Loader] is not instantiable while building
    [Flugg\Responder\Responder, Flugg\Responder\ErrorFactory,
    Flugg\Responder\ErrorMessageResolver, Illuminate\Translation\Translator].

      public function index(Responder $responder){
             $response = Experience::all();
             //return response($response,200);
             return responder()->success($response)->respond();
        }

**Comment by flugger** [comment]
Hey, what version of Lumen are you on?

**Comment by flugger** [comment]
I managed to replicate this with the latest version and this is indeed a library bug. Apparently some incompatibilities with the translator between Laravel and Lumen, but this should now be fixed with the just tagged release `v2.0.10`. Please run `composer update` and verify that it works, thanks!
