### ISSUE TITLE
Transforming nested relations

### ISSUE THREAD

**Issue by itcrowdmmgroup** [flugger/laravel-responder#69]
Hi,

I've been using your package for simple transformations on models. Now I want to go more advanced.

In my Controller I have:

>         $staff = staff::with('warfs.devices', 'tags_assignment.tags')->where('staff.uuid', '=', $staff_uuid)->first();

So some warfs have a device.

I want to transform my data that i only get the warfs.id and devices.uuid

In my transformer I have 

> class StaffTransformer extends Transformer
> {
> 
>     protected $load = [
>         'warfs.devices' => WarfsTransformer::class,
>         'tags_assignment.tags' => StaffTagsTransformer::class,
>     ];
> 
>      /**
>      * Transform the model data into a generic array.
>      *
>      * @param  staff $staff
>      * @return array
>      */
>     public function transform(staff $staff):array
>     {
>         return [
>             'uuid' => (string) $staff->uuid,
>             'firstname' => (string) $staff->firstname,
>         ];
>     }
> }
> 

In WarfsTransformer I have 

>     protected $relations = ['*'];
> 
>     /**
>      * Transform the model data into a generic array.
>      *
>      * @param  warfs $warfs
>      * @return array
>      */
>     public function transform(warfs $warfs):array
>     {
>         return [
>             'id' => (int) $warfs->id
>         ];
>     }
> 

However i receive all the columns on the warfs table when i transform the data:

> 
> {
> 	"data": {
> 		"uuid": "8EBB71E9-BCF2-4E5B-A95E-549F792C5BA7",
> 		"firstname": "Ken",
> 		"warfs": [{
> 			"id": 18,
> 			"uuid": "C90778D9-6B9F-4A6D-814F-7FC151E9DF4F",
> 			"warf_identifier": "***",
> 			"workplace_id": "***",
> 			"pivot": {
> 				"staff_id": 1,
> 				"warfs_id": 18
> 			},
> 			"devices": []
> 		}, {
> 			"id": 42,
> 			"warf_identifier": "***",
> 			"workplace_id": "***",
> 			"pivot": {
> 				"staff_id": 1,
> 				"warfs_id": 42
> 			},
> 			"devices": [{
> 				"id": 5,
> 				"uuid": "46497A88-42A6-438D-895B-541C6BD98A4D",
> 				"sn": "6530165100014",
> 			}]
> 		}],
> 		"tags_assignment": {
> 			"id": 5,
> 			"uuid": "1CAB4C9D-9213-4B26-A51E-32AECBA88221",
> 			"tags_id": 1,
> 			"staff_id": 1,
> 			"warfs_id": 0,
> 			"teams_id": 0,
> 			"tags": {
> 				"id": 1,
> 				"uuid": "68D566C2-09CC-4EAF-B80F-095664202249",
> 				"tag": "340062B83F",
> 				"tag_type": "SINGLE"
> 			}
> 		},
> 		"warfs.pivot": null,
> 		"warfs.devices": null,
> 		"warfs.devices.pivot": null,
> 		"tags_assignment.tags": null
> 	}
> }

What am I doing wrong?

**Comment by flugger** [comment]
In your `StaffTransformer` you have the following:

```php
protected $load = [
    'warfs.devices' => WarfsTransformer::class,
    'tags_assignment.tags' => StaffTagsTransformer::class,
];
```

The `devices` relation seems to be mapped to the `WarfsTransformer`. You can instead try to use non-nested relations:

```php
protected $load = [
    'warfs' => WarfsTransformer::class,
    'tags_assignment' => TagsAssignmentTransformer::class,
];
```

Then you can either move the `devices` and `tags` relation loading to the `WarfsTransformer` and `TagsAssignmentTransformer` respectively. Or, if you want to autoload the nested relations only from the `StaffTransformer` you should also be able to mix them:

```php
protected $load = [
    'warfs' => WarfsTransformer::class,
    'warfs.devices' => DevicesTransformer::class,
    'tags_assignment' => TagsAssignmentTransformer::class,
    'tags_assignment.tags' => StaffTagsTransformer::class,
];
```

Let me know if this solves your problems!

**Comment by itcrowdmmgroup** [comment]
Sorry, The problem still exists.

The first thing I did was upgrading to the latest version:

Composer.lock:

```           "name": "flugger/laravel-responder",
            "version": "v2.0.11",
            "source": {
                "type": "git",
                "url": "https://github.com/flugger/laravel-responder.git",
                "reference": "199e15d0ee9ac1ab6617267fd418d0fb8ed39938"
            },
````
Then for the sake of debugging I simplified my request. I only want the warfs assigned to a specific staff member:

StaffController:

````    php
        public function get_staff($staff_uuid) {
        $staff = staff::where('staff.uuid', '=', $staff_uuid)->first();
        return responder()->success($staff, StaffTransformer::class)->respond();
    }
````

StaffTransformer

````php

namespace App\Transformers;

use App\models\staff;
use App\Transformers\WarfsTransformer;
use Flugg\Responder\Transformers\Transformer;

class StaffTransformer extends Transformer
{
    /**
     * List of available relations.
     *
     * @var string[]
     */
    protected $relations = ['warfs'];

    /**
     * List of autoloaded default relations.
     *
     * @var array
     */
    protected $load = [
        'warfs' => WarfsTransformer::class,

    ];

    /**
     * Transform the model.
     *
     * @param  \App\models\staff $staff
     * @return array
     */
    public function transform(staff $staff)
    {
        return [
            'uuid' => (string) $staff->uuid,
            'firstname' => (string) $staff->firstname,
        ];
    }
}
````
WarfsTransformer
````php

namespace App\Transformers;

use App\models\warfs;
use Flugg\Responder\Transformers\Transformer;

class WarfsTransformer extends Transformer
{
    /**
     * List of available relations.
     *
     * @var string[]
     */
    protected $relations = ['*'];

    /**
     * List of autoloaded default relations.
     *
     * @var array
     */
    protected $load = [];

    /**
     * Transform the model.
     *
     * @param  \App\models\warfs $warfs
     * @return array
     */
    public function transform(warfs $warfs)
    {
        return [
            'uuid' => (string) $warfs->uuid,
        ];
    }
}
````

JSON-response:
```` json

{
    status: 200,
    success: true,
    data: {
    uuid: "8EBB71E9-BCF2-4E5B-A95E-549F792C5BA7",
    firstname: "Ken",
    warfs: [
        {
            id: 18,
            uuid: "C90778D9-6B9F-4A6D-814F-7FC151E9DF4F",
            warf_identifier: "TEST018",
            workplace_id: "9G4645224GVTW",
            street: "Thysstraat",
            number: "52",
            suffix: "",
            zipcode: "5397",
            municipality: "Spa",
            country: "BE",
            gps: "",
            created_at: null,
            updated_at: null,
            pivot: {
                staff_id: 1,
                warfs_id: 18
            }
        },
        {
            id: 1,
            uuid: "A83F0AFA-4F3C-4F6E-928D-C6FDF5DE2C2C",
            warf_identifier: "TEST001",
            workplace_id: "5B3089223YDMQ",
            street: "Laurentlaan",
            number: "63",
            suffix: null,
            zipcode: "2702",
            municipality: "Edingen",
            country: "BE",
            gps: null,
            created_at: null,
            updated_at: null,
            pivot: {
                staff_id: 1,
                warfs_id: 1
            }
        },
        {
            id: 40,
            uuid: "EC15B8B5-94AB-4B98-A692-5E2547983559",
            warf_identifier: "TEST040",
            workplace_id: "6J3472084PTEM",
            street: "Lievensring",
            number: "96",
            suffix: "",
            zipcode: "9523",
            municipality: "Hoei",
            country: "BE",
            gps: "",
            created_at: null,
            updated_at: null,
            pivot: {
                staff_id: 1,
                warfs_id: 40
            }
        }
    ]
}

So the WarfsTransformer isn't being applied

**Comment by flugger** [comment]
Hi again! I think the problem is that the transformer mapping in the `$load` property is only used for locating all nested relation's transformers to be able to eager load everything. It is currently not being used for transforming the data, so you would have to either map up a transformer to the Warfs model or making an `includeWarfs` method in your `StaffController`:

```php
public function includeWarfs(Staff $staff) {
    return $this->resource($staff->warfs, WarfsTransformer::class);
}
```

I do think, however, that this is a bit counter-intuitive to have to specify the transformer twice. I'll look into changing it

**Comment by itcrowdmmgroup** [comment]
Yes! 

This works. 

Thanks!
