### ISSUE TITLE
transform() helper

### ISSUE THREAD

**Issue by mitjarobic** [flugger/laravel-responder#75]
How do i use the transform helper since Laravel has one to?

https://laravel.com/docs/5.5/helpers#method-transform

**Comment by flugger** [comment]
Hi! I actually didn't realise 5.5 shipped with a new `transform` helper, that's a bummer. Not much else we can do but rename the helper to something like `transformer` and use it like `transformer()->transform($data)`, although it's a bit more verbose.

In the meantime, you may use the `Transformer` facade or inject the `Flugg\Responder\Transformer` service directly.

**Comment by flugger** [comment]
Not tagged a new release yet or updated the documentation, but the helper has now been updated with a new name and slightly new functionality. Earlier we could transform a product with included shipments and excluding orders:

```php
transform($product, new ProductTransformer, ['shipments'], ['orders']);
```

While this is short and precise, I feel like it has a way issues:

1. It's hard to understand what the 2 arrays are, are we including or excluding first?
2. If we don't want to explicitly assign a transformer, but relations we need to set parameter 2 to null. Not a good API!

So, I thought some about it and the `SuccessResponseBuilder` uses the `TransformBuilder` class behind the scenes to perform transformation methods. I thought I could take use of this to get a slightly nicer API without adding any new logic.

With that said, the new helper method works like following:

```php
transformation($user, new ProductTransformer)->with('shipments')->without('orders')->transform();
```

This solves the name-collision with Laravel 5.5 by introducing a new name: `transformation` and it solves point 1 and 2 above. 

I'll tag a major release soon with updated changelog and documentation for more information :)

**Comment by flugger** [comment]
`3.0.0` has now been released and it includes the new `transformation` helper as noted above!
