### ISSUE TITLE
Calling multiple transformers in sequence

### ISSUE THREAD

**Issue by mitjarobic** [flugger/laravel-responder#76]
Lets say $model1 has a relationship 'shipments', $model2 has none. Transformer2 would throw a RelationNotFoundException exception looking for relation 'shipments' on $model2.

Transformer::transform($model1, new Transformer1);
Transformer::transform($model2, new Transformer2);

"exception":"Illuminate\\Database\\Eloquent\\RelationNotFoundException",
"file":"/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/RelationNotFoundException.php",
"line": 34,

**Comment by flugger** [comment]
This sounds like a similar issue that was fixed in a recent version. What version of the package are you using?

**Comment by flugger** [comment]
Hey, with the latest `3.0.0` release this should be fixed! Let me know if you still have problems
