### ISSUE TITLE
Passing Array That Contains Model Instance Will Only Pass The Model To Transformer

### ISSUE THREAD

**Issue by brunogaspar** [flugger/laravel-responder#77]
Hello

I've found an issue.

```php
<?php

namespace App\Transformers;

class AuthenticatedUserTransformer extends Transformer
{
    public function transform(array $payload)
    {
        $user = (new UserTransformer())->transform($payload['user']);

        $token = $payload['token'];

        return compact('user', 'token');
    }
}
```

```php
$data = [
    'user' => User::find(1),
    'token' => 'foo',
];

return responder()
    ->success($data, new UserAuthenticatedTransformer())
    ->respond(SymfonyResponse::HTTP_OK, $headers)
;
```

Basically what happens is that, internally if it finds an Eloquent model, it assumes wrongly that's what's supposed to be passed to the transformer.
Obviously that's not correct as i'm passing an array, so i'm expecting to receive that same array on the transformer.

If i remove the type hint on the transformer, i see that only the User instance is passed and the token string is not passed.

Any clues to solve this?

Thanks!

**Comment by flugger** [comment]
Hi! The package creates a Fractal collection resource if the data provided is an array of objects or implements Traverseable. An option is to check if the array has associative keys, if so, we’ll treat it as an item resource. This could, however, potentially be a breaking change. I’ll look into it, thanks!

**Comment by brunogaspar** [comment]
Maybe something to turn the feature off that would be turned on by default?

That wouldn't case a breaking change, however, i don't see this as a breaking change as that's not really how it should behave, but leaving it up to you :)

**Comment by flugger** [comment]
It should be noted that this is only the case for associative arrays containing an Eloquent model as the first item. In other cases, an associative array is treated as an item resource by default. I think this should be changed to only default to a collection resource, if the first item is an Eloquent model _and_ the array is not associative.

**Comment by brunogaspar** [comment]
Thanks, that will do for now :)

**Comment by brunogaspar** [comment]
Just a heads up that the following also fails:

```php
$data = [
    'timestamp' => \Carbon\Carbon::now(),
];

return responder()->success($data)->respond();
```

`Type error: Argument 1 passed to League\\Fractal\\Scope::filterFieldsets() must be of the type array, object given, called in /Users/bruno/Dropbox/Werxe/Projetos/GitHub/werxe/laravel-api-starter-kit/vendor/league/fractal/src/Scope.php on line 385`

I'm using the temporary solution for now..

**Comment by flugger** [comment]
With the latest `3.0.0` release this should also have been fixed!
