### ISSUE TITLE
Support Fractal v0.17

### ISSUE THREAD

**Issue by kevmt** [flugger/laravel-responder#78]
Hi,

I cant install the package because of `league/fractal: ^0.16.0` please update to `0.17.0` if possible.

Thanks

**Comment by flugger** [comment]
Hi @kevmt! As far as I know, `^0.16.0` should mean `0.16.0` or higher, so it should be fine with `0.17.0`. What errors are you receiving?

**Comment by kevmt** [comment]
@flugger It shows about `...don't install 0.16.0...` I guess its composer bug.

**Comment by IlCallo** [comment]
@flugger 

> For pre-1.0 versions it also acts with safety in mind and treats ^0.3 as >=0.3.0 <0.4.0.

[https://getcomposer.org/doc/articles/versions.md#caret-version-range-](source)

If you could update the composer.json, it would be better. I got stuck in a similar error @kevmt got

**Comment by flugger** [comment]
Oh, good to know, thanks! I’ll reopen this and update the composer to v0.17 soon. Sorry for the inconvenience!

**Comment by IlCallo** [comment]
Thank you :)

**Comment by kevmt** [comment]
@IlCallo Thank you for pointing out, I was going to re-open this issue. I also got stock on this due to dingo/api which uses `league/fractal: ^0.17`

@flugger Please change this soon.  I forked your library internally and change it to `^0.17` and it is working just fine.

**Comment by IlCallo** [comment]
I think he's taking some time to integrate new features of Fractal 0.17 into laravel-responder (like primitive resources etc.)

**Comment by flugger** [comment]
Yes! What @IlCallo said basically - there will be a release very soon :)

**Comment by flugger** [comment]
With `v3.0.0` the package now supports Fractal `v0.17.0` - sorry for taking so long!
