### ISSUE TITLE
return responder()->success(Product::all())->only('id', 'name')->respond();

### ISSUE THREAD

**Issue by Hesesses** [flugger/laravel-responder#79]
If Products is empty, then i'm getting error
`"Filtering fields using sparse fieldsets require resource key to be set."`

**Comment by flugger** [comment]
Hey @Hesesses!

From v2.0.5 I added automatic resource key resolving, do you happen to have an earlier version?

**Comment by flugger** [comment]
Oh, nevermind, I see now that the resource key resolving doesn't work when there's no model to resolve a resource key from.

**Comment by flugger** [comment]
Upon further investigation, Fractal currently requires a resource key when using sparse fieldsets even if there's no data to filter. I think it can be solved easily by giving all empty collections a default resource key, I'll look more deeply into it later!

**Comment by Hesesses** [comment]
Thank you 👍

**Comment by flugger** [comment]
With the latest `3.0.0` release this should be fixed. Let me know if you still have issues :)
