### ISSUE TITLE
Pretty Json by default

### ISSUE THREAD

**Issue by IlCallo** [flugger/laravel-responder#80]
I've just started watching at this great package, previously I used `return response()->prettyJson($data)`  where the "prettyJson" was a response macro I defined to return JSON_PRETTY_PRINT option enabled by default.

Is it possible to do a similar thing with this package? `respond()` method doesn't accept options like `Response::json()` do, as far I've seen.

In particular, a way to enable pretty print by default (maybe in the config file?) would be much appreciated

**Comment by IlCallo** [comment]
I see, didn't noticed that that method called toArray which called respond()...
The use case is just that I prefer to return json data pretty printed by default, at least while developing.
Of course it's not a big deal, I'll just use toJson, thank you anyway :)

**Comment by flugger** [comment]
Yeah, using `respond` and `toJson` is practically the same. In case you’re using Chrome, have you seen this plugin: https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa?hl=en ? It will automatically render the JSON beautifully :)

**Comment by IlCallo** [comment]
Yeah, I already have a plugin enabled for JSON, but I cannot expect everybody else to install it as well, that's why I prefer producing prettified JSON by default when I can

**Comment by flugger** [comment]
Hey again! The problem with using `toJson` is that you currently have no way of setting status code other than the `respond()` method, as the `setStatusCode` method is protected. This can be changed to public, but I still feel like using `respond()` is a cleaner solution. So, I've been looking more deeply into this and seeing the `respond()` method returns an `Illuminate\Http\JsonResponse` and not pure JSON, I don't feel a default configuration makes too much sense. However, this might be a perfect fit for a response decorator (as seen [here](https://github.com/flugger/laravel-responder#decorating-response)). Here is an example:

```php
<?php
class PrettyPrintDecorator extends ResponseDecorator
{
    public function make(array $data, int $status, array $headers = []): JsonResponse
    {
        $response = $this->factory->make(array_merge([
            'status' => $status,
        ], $data), $status, $headers);

        $response->setEncodingOptions($response->getEncodingOptions() | JSON_PRETTY_PRINT);

        return $response;
    }
}
```

Let me know if this solves your problems!

**Comment by IlCallo** [comment]
That seems perfect!
I guess you meant

    <?php
    class PrettyPrintDecorator extends ResponseDecorator
    {
        public function make(array $data, int $status, array $headers = []): JsonResponse
        {
            $response = $this->factory->make($data, $status, $headers);
    
            $response->setEncodingOptions($response->getEncodingOptions() | JSON_PRETTY_PRINT);
    
            return $response;
        }
    }

and that the array_merge for "status" field was from a copy/paste of the StatusCodeDecorator.

Are you gonna insert it into the library amongst other decorators in next release?

**Comment by flugger** [comment]
Yeah, sorry, I did indeed copy/paste it from the status code decorator and was a bit

**Comment by IlCallo** [comment]
Ok, I'll wait for the release then, I'm in no hurry, ty :)

**Comment by IlCallo** [comment]
I guess this can be closed
