### ISSUE TITLE
Usage of includeXxx parameters

### ISSUE THREAD

**Issue by IlCallo** [flugger/laravel-responder#83]
In Fractal it's possible to give includeXxx methods a ParamBag containing parameters (even if it isn't very clear about it).
Even in the documentation of laravel-responder there is an example which takes in an array (instead of a ParamBag), but it isn't explained how to use them in any way...

I tryed calling the `with()` method with the param syntax of fractal like 
`->with('roles:param(value1|value2)')`
but I got an error in response.

Is there a way to actually provide parameters to an includeXxx method on a transformer class when using a `return responder()->success($data)->respond()` chain in a controller method?

**Comment by flugger** [comment]
Ahh, just tested this out and realised this doesn't work as intended. Basically, Fractal's `parseIncludes` method will do the parsing of parameters. However, the package calls this method after setting available relations on the transformer(s), meaning it will try to include relations in the transformer with the full parameter query which obviously fails. I think the easiest way of solving it is to strip out the parameters only when setting available relations, then send the untouched relation with parameters to Fractal for parsing. Sorry for the issues, I'll get this sorted as soon as possible!

**Comment by flugger** [comment]
Also, the package converts the ParamBag to an array before passing it the includeXXX methods in an effort to stay as decoupled from Fractal as possible.

**Comment by IlCallo** [comment]
> Also, the package converts the ParamBag to an array before passing it the includeXXX methods in an effort to stay as decoupled from Fractal as possible.

Good idea!

> Sorry for the issues, I'll get this sorted as soon as possible!

You've done a great job doing this and releasing it under MIT license, I don't think you shall feel "sorry" in any way :P
I'll just wait for the fix (I'll start contributing to the library myself when I finish exploring it in depth probably, just to avoid to mess everything up), the one you proposed seems simple and straight so it must be the right one :)

**Comment by IlCallo** [comment]
Also, I would add a small paragraph about this feature (and the fact that it returns an array and not a ParamBag) in the docs if possible

**Comment by flugger** [comment]
Appreciate the kind words! And yeah, I'll get it fixed and added to the documentation, must have slipped my mind when writing it

**Comment by IlCallo** [comment]
I fixed this following the hint you gave.
I added a function at the end of `TransformBuilder` like this

    /**
     * Remove parameters from relations that must be loaded.
     *
     * @return array
     */
    protected function relationsWithoutParameters(): array
    {
        return array_map(function($value) {
            return explode(':', $value)[0];
        }, $this->with);
    }

And [here](https://github.com/flugger/laravel-responder/blob/40e987951b112e50ff35805817871f707bda2c23/src/TransformBuilder.php#L254) i changed

    $data->load($this->with);

with
    $data->load($this->relationsWithoutParameters());

Now it works fine.
If you don't have time to do it, next week I'll probably clone the repository, add tests and create pull requests
