### ISSUE TITLE
Serializer changed when using transform() helper inside a Transformer

### ISSUE THREAD

**Issue by IlCallo** [flugger/laravel-responder#86]
Hey, another use case, another bug :D
One of my models have a relation that I want to resolve in the transform() method of it's Transformer, because I know that it is already eager loaded and mostly because I don't want people (aka myself in 2-3 months) to be able to take it away from the response with a "without()" call when returning the response.

To do this I decided to use the `transform()` helper inside the `transform()` method of the Transformer.
It worked, but now data are serialized as 

    ['things' => /things_content/]

instead of

    ['data' => ['things' => /things_content/]]

as SuccessSerializer would require.
I dug deeper and apparently it seems like the `transform()` method I call shares somehow it's Fractal `Manager` reference (which holds the reference to the serializer to use) with the currently resolving `success()` response generator.
`transform()` helper uses `NullSerializer` and when I call it inside the `transform()` method it probably overwrite the `SuccessSerializer` reference set by the `success()` method, ruining the output.

Is this possible? How can this be fixed?

**Comment by IlCallo** [comment]
Temporary workaround, moving manually the data (except for decorators) inside the 'data' namespace.

    // TODO remove when transform() helper stops overwriting SuccessSerializer when used inside the transformer
    $wrongResponse = responder()->success($model, GuiltyTransformer::class)->toArray();
    return new JsonResponse([
        'status' => $wrongResponse['status'],
        'success' => $wrongResponse['success'],
        'data' => array_except($wrongResponse, ['status', 'success']),
    ]);

**Comment by flugger** [comment]
The Fractal manager shouldn't be a singleton, so this does sound strange. I'll look into it and see what I find out

**Comment by IlCallo** [comment]
Yeah, that seems strange to me too, but that's the only idea I could get to... I'll try to dig deeper tomorrow

**Comment by IlCallo** [comment]
Forgot to mention that the workaround I wrote still uses NullSerializer, so null values are being converted as empty arrays because of #82

**Comment by IlCallo** [comment]
You were right: Fractal `Manager` isn't a singleton, but the `TransformFactory` you register is.
[Here you can see the binding](https://github.com/flugger/laravel-responder/blob/40e987951b112e50ff35805817871f707bda2c23/src/ResponderServiceProvider.php#L215)
Given that `TransformFactory` is a singleton and it holds a reference to the `Manager`, the same `Manager` is used for **all** transformations and when it's used for the `transform()` helper, the serializer is changed for all others "pending" transformations.

I changed from `singleton()` to `bind()` and the problem seem gone.
Of course this will create a new `FractalTransformFactory` for every transform request, is that a big performance problem?

**Comment by flugger** [comment]
Ahh. Of course! And no, that shouldnt be a problem at all, as the TransformFactory only happens once for every response (or use of the `transform` method). Thanks for finding the error, sounds like an easy fix :)

**Comment by flugger** [comment]
I believe this will fix this issue as well: https://github.com/flugger/laravel-responder/issues/76

**Comment by IlCallo** [comment]
I'll work on this one tomorrow, even if I'm pretty confused on how to create a test for this bugfix following your test style 🤔
Then I'll take down #82 if I have enough time

**Comment by flugger** [comment]
I'm planning on writing a feature/integration test suite when I have time which will make it easier to test those higher level scenarios. I agree it doesn't really make sense with a unit test for this, so just leave the test for now, I'll add a note on it for the feature tests, it's just a small change anyway.
