### ISSUE TITLE
Return simple array on Success method

### ISSUE THREAD

**Issue by traycer** [flugger/laravel-responder#93]
Hi everyone, i have a question, i'm trying to return a simple array in the success method, as it's part of my authentication flow, but for some reason the returned data loses the associative array keys that i set.

     return responder()->success(collect([
            'user' => $this->guard()->user(),
            'jwt'  => [
                'expires_at' => $this->getExpirationTime($token),
                'token'      => $token
            ]
        ]))->respond(200, ["Authorization" => "Bearer {$token}"]);

That's my code, and for some reason all i get is two unnamed objects, it loses the 'user' and 'jwt' keys entirely, is this expected behavior? If so how can you just return a simple array? I don't want to use response()->json() alongside responder as that defeats the purpose of setting global decorators and a standard format using responder.

**Comment by flugger** [comment]
Hi @smtlk! This issue has already been raised (https://github.com/flugger/laravel-responder/issues/77) and a fix is on its way. A temporary solution is to pass in a  `League\Fractal\Item` object like this:

```php
return responder()->success(new Item([
        'user' => $this->guard()->user(),
        'jwt'  => [
            'expires_at' => $this->getExpirationTime($token),
            'token'      => $token
        ]
    ]))->respond(200, ["Authorization" => "Bearer {$token}"]);
```

**Comment by flugger** [comment]
With the latest `3.0.0` release this has now been fixed
