### ISSUE TITLE
I'm getting this error. I use Php 7.2

### ISSUE THREAD

**Issue by mauricemojito** [flugger/laravel-responder#94]
[message": "count(): Parameter must be an array or an object that implements Countable",
    "exception": "ErrorException",
    "file": "/home/forge/pornhub.com/vendor/flugger/laravel-responder/src/Transformers/Concerns/MakesResources.php",](url)

**Comment by flugger** [comment]
Hi! What data are you passing to the responder? At the moment you can only pass in arrays or objects (collections) as data. However, Fractal recently got support for primitive resources allowing all kinds of data. This should be supported by new year

**Comment by mauricemojito** [comment]
@flugger I fixed it 👍  I returned an array in a transformer and include it to an another transformer(The error occurred here), than I just made an hasMany relationship. Since It worked in php 7.18 I was wondering why it didn't failed, than I saw that they changed the behavior of the count function in php 7.2. Thank you for the answer
