### ISSUE TITLE
[Bug] Relations inclusion and PHP7.2

### ISSUE THREAD

**Issue by IlCallo** [flugger/laravel-responder#95]
Into [MakesResources](https://github.com/flugger/laravel-responder/blob/fe348d053ab6cae9409d9fe8f09282ecfe2aa716/src/Transformers/Concerns/MakesResources.php#L75) the `count()` function is used to check for countability (or it seems so).
From PHP7.2 onwards, using `count()` over not countable objects will result in an error.
Is it possible to change it to `is_array($data) || $data instanceof Countable` or something similar? 
Do you think it'll break something? If the same is used in other parts of the code for the same purpose, it must be changed as well.

**Comment by IlCallo** [comment]
Ok, I tried to change
`if (! count($data)) {`
to
`if (! is_array($data) && ! $data instanceof Countable) {`
and everything worked as expected.

Shall I make a PR for this? Have you found some time to work on the library?  @flugger

**Comment by flugger** [comment]
Hi! Yes, that looks like a good solution, I’ll gladly accept a PR! 

I’ve started digging at some fixes to various issues and you may expect a minor release in the not so distant future. Happy New Years! 🎉
