### ISSUE TITLE
TransformBuilder is shared and dirty between Flugg\Responder\Contracts\Transformer calls

### ISSUE THREAD

**Issue by IlCallo** [flugger/laravel-responder#97]
Another year, another bug!
In my Transformers I used to transform manually other pieces of data using the helper, while waiting for updates on other issues.
While migrating to L5.5 (on PHP7.2, but I don't think the PHP version influences the result) a strange behaviour started happening in those transformations.
First of all I needed to start using the Facade method because of L5.5 `transform()` new helper overwrites this package helper.
I noticed that when I called multiple times the `Transformer` facade, I got some errors of undefined relations on my classes.
After a lot of debugging, I found that the same instance of the class implementing `Flugg\Responder\Contracts\Transformer` were used betweed different calls (I highly suggest to provide different names, it's hard to explain something with 2-3 classes with the same name) and shared the same `TransformBuilder` instance, which was not cleaned between uses.
In this way the `$with` property of the instance kept the relations values of the previous transformation, searching them on the model of the next transformation, causing an error.

To solve it temporarly, I removed the `TransformBuilder` auto-injection and property and told the `Flugg\Responder\Contracts\Transformer` instance to always generate a new `TransformBuilder` for every transformation.

    public function transform($data = null, $transformer = null, array $with = [], array $without = []): array
    {
        return app(TransformBuilder::class)->resource($data, $transformer)
            ->with($with)
            ->without($without)
            ->serializer(new NullSerializer)
            ->transform();
    }

I don't recall having this problem on L5.4 with PHP7.1, everything just worked fine.
I can suppose either one of the two:
- the bug was there previously but L5.4 just let it fail silently when a wrong relation was asked to load;
- the bug derives by L5.5 update.

Any other idea/better way to fix this, before I make a PR? I tried to fix it acting on the `ResponderServiceProvider` but I could not find a way to generate a new `Flugg\Responder\Contracts\Transformer` instance for every transformation call.

**Comment by flugger** [comment]
Hmm, sounds like the same issue as this issue which was raised earlier: https://github.com/flugger/laravel-responder/issues/76

I’ll look into it!

**Comment by IlCallo** [comment]
Ok, thank you!

**Comment by mitjarobic** [comment]
any updates on this?

**Comment by IlCallo** [comment]
We needed this in production and created a little script which automatically apply the temporary fix I wrote up there after the composer install.
You can follow the same path I guess, unless @flugger accept a PR with this temporary fix while he tries to fix it in a better way.

**Comment by flugger** [comment]
This should now be fixed with the latest `3.0.0` release :)
